import BanLat.Preliminaries.SignedMeasure
import BanLat.Examples.CofK
import Mathlib.MeasureTheory.Measure.Regular
import Mathlib.MeasureTheory.Integral.Regular
import Mathlib.Topology.ContinuousMap.Basic
import Mathlib.Topology.UrysohnsLemma
import Mathlib.Topology.Separation.GDelta
import Mathlib.Topology.Metrizable.Urysohn

/-!
# The Baire σ-algebra

The Baire σ-algebra on a topological space is the coarsest σ-algebra making all
continuous real-valued functions measurable. On a compact Hausdorff space it
coincides with the σ-algebra generated by compact Gδ sets, and every finite
signed Baire measure extends uniquely to a regular signed Borel measure.
-/

noncomputable section

open MeasureTheory Set

variable {α : Type*} [TopologicalSpace α]

/-- The Baire σ-algebra on a topological space, defined as the coarsest
σ-algebra making all continuous real-valued functions measurable. -/
def baire (α : Type*) [TopologicalSpace α] : MeasurableSpace α :=
  ⨆ (f : C(α, ℝ)), MeasurableSpace.comap f (borel ℝ)

/-- Asserts that the ambient `MeasurableSpace` equals the Baire σ-algebra.
Analogous to `BorelSpace` for the Borel σ-algebra. Not to be confused with the
topological `BaireSpace` (Baire category theorem). -/
class BaireMeasureSpace (α : Type*) [TopologicalSpace α]
    [MeasurableSpace α] : Prop where
  measurable_eq : ‹MeasurableSpace α› = baire α

/-- The Baire σ-algebra is contained in the Borel σ-algebra. -/
theorem baire_le_borel : baire α ≤ borel α :=
  iSup_le fun f => f.continuous.borel_measurable.comap_le

private lemma isGδ_preimage {β : Type*} [TopologicalSpace β]
    {f : α → β} (hf : Continuous f) {s : Set β} (hs : IsGδ s) :
    IsGδ (f ⁻¹' s) := by
  obtain ⟨T, hT_open, hT_count, hTs⟩ := hs
  refine ⟨(f ⁻¹' ·) '' T, ?_, hT_count.image _, ?_⟩
  · rintro _ ⟨t, ht, rfl⟩; exact (hT_open t ht).preimage hf
  · rw [hTs, Set.preimage_sInter, Set.sInter_image]

private lemma generateFrom_isCompact_isGδ_le_baire
    [CompactSpace α] [T2Space α] :
    MeasurableSpace.generateFrom {K : Set α | IsCompact K ∧ IsGδ K} ≤ baire α := by
  apply MeasurableSpace.generateFrom_le
  rintro K ⟨hK, hGδ⟩
  obtain ⟨f, hK_eq, -, -, -⟩ :=
    exists_continuous_one_zero_of_isCompact_of_isGδ hK hGδ isClosed_empty
      (disjoint_empty K)
  rw [hK_eq]
  apply le_iSup (fun (g : C(α, ℝ)) => MeasurableSpace.comap g (borel ℝ)) f
  exact ⟨{1}, BorelSpace.measurable_eq (α := ℝ) ▸ measurableSet_singleton 1, rfl⟩

private lemma baire_le_generateFrom_isCompact_isGδ
    [CompactSpace α] [T2Space α] :
    baire α ≤
      MeasurableSpace.generateFrom {K : Set α | IsCompact K ∧ IsGδ K} := by
  apply iSup_le
  intro f
  rw [show borel ℝ = MeasurableSpace.generateFrom {s : Set ℝ | IsOpen s} from rfl,
      MeasurableSpace.comap_generateFrom]
  apply MeasurableSpace.generateFrom_le
  rintro _ ⟨U, hU : IsOpen U, rfl⟩
  rw [show f ⁻¹' U = (f ⁻¹' Uᶜ)ᶜ from by simp [Set.preimage_compl]]
  apply MeasurableSet.compl
  apply MeasurableSpace.measurableSet_generateFrom
  exact ⟨(hU.isClosed_compl.preimage f.continuous).isCompact,
    isGδ_preimage f.continuous hU.isClosed_compl.isGδ⟩

/-- In a compact Hausdorff space, the Baire σ-algebra is generated by compact Gδ
sets. -/
theorem baire_eq_generateFrom_isCompact_isGδ
    [CompactSpace α] [T2Space α] :
    baire α =
      MeasurableSpace.generateFrom
        {K : Set α | IsCompact K ∧ IsGδ K} :=
  le_antisymm baire_le_generateFrom_isCompact_isGδ generateFrom_isCompact_isGδ_le_baire

section BaireMeasureSpace

variable [MeasurableSpace α] [bms : BaireMeasureSpace α]
include bms

/-- A continuous real-valued function is Baire measurable. -/
theorem ContinuousMap.measurable_baire (f : C(α, ℝ)) :
    Measurable f := by
  rw [measurable_iff_comap_le, bms.measurable_eq, BorelSpace.measurable_eq (α := ℝ)]
  exact le_iSup (fun (g : C(α, ℝ)) => MeasurableSpace.comap g (borel ℝ)) f

/-- In a compact Hausdorff space, a compact Gδ set is Baire measurable. -/
theorem IsCompact.baire_measurableSet
    [CompactSpace α] [T2Space α] {K : Set α}
    (hK : IsCompact K) (hGδ : IsGδ K) :
    MeasurableSet K := by
  rw [bms.measurable_eq, baire_eq_generateFrom_isCompact_isGδ]
  exact MeasurableSpace.measurableSet_generateFrom ⟨hK, hGδ⟩

end BaireMeasureSpace

namespace BaireMeasure

variable [CompactSpace α] [T2Space α]

private noncomputable def baireIntegral
    (μ : @Measure α (baire α)) (f : C(α, ℝ)) : ℝ :=
  @integral α ℝ _ _ (baire α) μ (fun x => f x)

omit [T2Space α] in
private theorem baireIntegral_continuous_integrable
    (μ : @Measure α (baire α)) [@IsFiniteMeasure α (baire α) μ]
    (f : C(α, ℝ)) :
    Integrable (fun x => f x) μ := by
  letI : MeasurableSpace α := baire α
  exact Integrable.of_bound
    (Measurable.aestronglyMeasurable (by
      rw [measurable_iff_comap_le]
      exact le_iSup (fun g : C(α, ℝ) => MeasurableSpace.comap (⇑g) (borel ℝ)) f))
    ‖f‖ (Filter.Eventually.of_forall (ContinuousMap.norm_coe_le_norm f))

private noncomputable def baireSignedMeasureLinearMap
    (s : @SignedMeasure α (baire α)) : C(α, ℝ) →ₗ[ℝ] ℝ := by
  letI : MeasurableSpace α := baire α
  exact
    { toFun := fun f =>
        baireIntegral s.toJordanDecomposition.posPart f -
          baireIntegral s.toJordanDecomposition.negPart f
      map_add' := fun f g => by
        simp only [baireIntegral, ContinuousMap.add_apply]
        have hp := baireIntegral_continuous_integrable s.toJordanDecomposition.posPart
        have hn := baireIntegral_continuous_integrable s.toJordanDecomposition.negPart
        rw [integral_add (hp f) (hp g), integral_add (hn f) (hn g)]
        ring
      map_smul' := fun c f => by
        simp only [baireIntegral, ContinuousMap.smul_apply, smul_eq_mul,
          RingHom.id_apply, integral_const_mul]
        ring }

omit [T2Space α] in
private theorem baireSignedMeasureLinearMap_norm_bound
    (s : @SignedMeasure α (baire α)) (f : C(α, ℝ)) :
    ‖baireSignedMeasureLinearMap s f‖ ≤
      (@SignedMeasure.totalVariation α (baire α) s Set.univ).toReal * ‖f‖ := by
  letI : MeasurableSpace α := baire α
  set j := s.toJordanDecomposition
  have hbound : ∀ x, ‖f x‖ ≤ ‖f‖ := ContinuousMap.norm_coe_le_norm f
  have h₁ : ‖baireIntegral j.posPart f‖ ≤ ‖f‖ * (j.posPart Set.univ).toReal := by
    haveI := j.posPart_finite
    unfold baireIntegral
    exact (norm_integral_le_of_norm_le_const (Filter.Eventually.of_forall hbound)).trans_eq
      (by rw [Measure.real])
  have h₂ : ‖baireIntegral j.negPart f‖ ≤ ‖f‖ * (j.negPart Set.univ).toReal := by
    haveI := j.negPart_finite
    unfold baireIntegral
    exact (norm_integral_le_of_norm_le_const (Filter.Eventually.of_forall hbound)).trans_eq
      (by rw [Measure.real])
  have hnorm : (s.totalVariation Set.univ).toReal =
      (j.posPart Set.univ).toReal + (j.negPart Set.univ).toReal := by
    rw [SignedMeasure.totalVariation, Measure.add_apply,
      ENNReal.toReal_add (measure_ne_top _ _) (measure_ne_top _ _)]
  show ‖baireIntegral j.posPart f - baireIntegral j.negPart f‖ ≤ _
  calc ‖baireIntegral j.posPart f - baireIntegral j.negPart f‖
      ≤ ‖baireIntegral j.posPart f‖ + ‖baireIntegral j.negPart f‖ := norm_sub_le _ _
    _ ≤ ‖f‖ * (j.posPart Set.univ).toReal +
          ‖f‖ * (j.negPart Set.univ).toReal := add_le_add h₁ h₂
    _ = _ := by rw [hnorm]; ring

/-- Extension of a signed Baire measure on a compact Hausdorff space to a
signed Borel measure, constructed via the Riesz representation theorem. -/
noncomputable def borelExtension [Nonempty α]
    (s : @SignedMeasure α (baire α)) :
    @SignedMeasure α (borel α) :=
  letI : MeasurableSpace α := borel α
  haveI : BorelSpace α := ⟨rfl⟩
  rieszSignedMeasure
    ((baireSignedMeasureLinearMap s).mkContinuous
      _ (baireSignedMeasureLinearMap_norm_bound s))

/-- The signed Borel extension is a regular signed measure. -/
theorem borelExtension_regular [Nonempty α]
    (s : @SignedMeasure α (baire α)) :
    @SignedMeasure.IsRegular α _ (borel α) (borelExtension s) := by
  letI : MeasurableSpace α := borel α
  haveI : BorelSpace α := ⟨rfl⟩
  unfold borelExtension
  exact rieszSignedMeasure_isRegular _

-- Auxiliary lemmas for borelExtension_apply

omit [CompactSpace α] [T2Space α] in
/-- For any Gδ set, there is a monotone-decreasing sequence of open sets whose intersection
equals it. -/
private lemma isGδ_monotone_opens {K : Set α} (hGδ : IsGδ K) :
    ∃ (U : ℕ → Set α), (∀ n, IsOpen (U n)) ∧ (∀ n, U (n + 1) ⊆ U n) ∧ K = ⋂ n, U n := by
  obtain ⟨V, hV_open, hV_eq⟩ := hGδ.eq_iInter_nat
  refine ⟨fun n => ⋂ i ∈ Finset.range (n + 1), V i,
    fun n => isOpen_biInter_finset (fun i _ => hV_open i),
    fun n x hx => ?_, ?_⟩
  · simp only [Finset.mem_range, Set.mem_iInter] at hx ⊢
    exact fun i hi => hx i (Nat.lt_succ_of_lt hi)
  · rw [hV_eq]; ext x; simp only [Set.mem_iInter, Finset.mem_range]
    exact ⟨fun h n i _ => h i, fun h n => h n n (Nat.lt_succ_self n)⟩

omit [CompactSpace α] [T2Space α] in
/-- Compact Gδ sets form a pi-system on a T2 space. -/
private lemma isPiSystem_isCompact_isGδ [CompactSpace α] [T2Space α] :
    IsPiSystem {K : Set α | IsCompact K ∧ IsGδ K} := by
  intro A ⟨hAc, hAg⟩ B ⟨hBc, hBg⟩ hne
  exact ⟨hAc.inter_right hBc.isClosed, hAg.inter hBg⟩

/-- For a compact Gδ set K and a finite baire measure μ, the Riesz Borel extension ν of μ
satisfies `ν K = μ K` as ENNReal values. -/
private lemma rieszMeasure_eq_baire_of_compact_gδ
    (μ : @Measure α (baire α)) [@IsFiniteMeasure α (baire α) μ]
    (φ : NormDualSpace C(α, ℝ)) (hφ : 0 ≤ φ)
    (hφ_eq : ∀ f : C(α, ℝ), φ f = baireIntegral μ f)
    {K : Set α} (hK : IsCompact K) (hGδ : IsGδ K) :
    letI : MeasurableSpace α := borel α
    letI : BorelSpace α := ⟨rfl⟩
    (rieszMeasureOfNonneg φ hφ) K = μ K := by
  letI : MeasurableSpace α := borel α
  letI : BorelSpace α := ⟨rfl⟩
  set ν := rieszMeasureOfNonneg φ hφ with hν_def
  -- Key identity: ∫(borel) f dν = ∫(baire) f dμ for all continuous f
  have hbaire_eq : ∀ f : C(α, ℝ),
      ∫ x, f x ∂ν = baireIntegral μ f := fun f => by
    rw [← hφ_eq f]; exact integral_rieszMeasureOfNonneg φ hφ f
  -- ν K = ⨅ {∫(borel) f dν | f continuous, compactly supported, f = 1 on K, f ≥ 0}
  rw [hK.measure_eq_biInf_integral_hasCompactSupport ν]
  apply le_antisymm
  · -- Upper bound: a Urysohn sequence gₙ satisfying gₙ = 1 on K and supp(gₙ) ⊆ Uₙ ↘ K
    -- converges pointwise to 1_K; DCT gives ∫ gₙ dμ → μ K; so iInf ≤ μ K.
    obtain ⟨U, hU_open, hU_mono, hU_inter⟩ := isGδ_monotone_opens hGδ
    have hKUn : ∀ n, Disjoint K (U n)ᶜ := fun n => by
      rw [Set.disjoint_compl_right_iff_subset]; intro x hxK
      have : x ∈ ⋂ n, U n := hU_inter ▸ hxK
      exact Set.mem_iInter.mp this n
    choose g hg_one hg_zero hg_supp hg_range using
      fun n => exists_continuous_one_zero_of_isCompact hK (hU_open n).isClosed_compl (hKUn n)
    -- DCT: baireIntegral μ (gₙ) → (μ K).toReal
    have h_dct : Filter.Tendsto (fun n => baireIntegral μ (g n))
        Filter.atTop (nhds (μ K).toReal) := by
      letI hbms : MeasurableSpace α := baire α
      have hKm : @MeasurableSet α (baire α) K := by
        rw [baire_eq_generateFrom_isCompact_isGδ]
        exact MeasurableSpace.measurableSet_generateFrom ⟨hK, hGδ⟩
      rw [show (μ K).toReal = ∫ x, Set.indicator K (1 : α → ℝ) x ∂μ from
        (integral_indicator_one hKm).symm]
      apply tendsto_integral_of_dominated_convergence (bound := fun _ => 1)
      · intro n
        have : @Measurable α ℝ (baire α) (borel ℝ) (g n) := by
          rw [measurable_iff_comap_le]
          exact le_iSup (fun f : C(α, ℝ) => MeasurableSpace.comap (⇑f) (borel ℝ)) (g n)
        exact this.aestronglyMeasurable
      · exact integrable_const 1
      · intro n; exact Filter.Eventually.of_forall fun x => by
          simp only [Real.norm_eq_abs, abs_le]
          exact ⟨by linarith [(hg_range n x).1], (hg_range n x).2⟩
      · apply Filter.Eventually.of_forall; intro x
        by_cases hxK : x ∈ K
        · simp only [Set.indicator_of_mem hxK, Pi.one_apply]
          exact tendsto_const_nhds.congr' (Filter.Eventually.of_forall fun n => (hg_one n hxK).symm)
        · simp only [Set.indicator_of_notMem hxK]
          rw [hU_inter] at hxK
          simp only [Set.mem_iInter, not_forall] at hxK
          obtain ⟨m, hxUm⟩ := hxK
          have hUanti : Antitone U := antitone_nat_of_succ_le hU_mono
          exact tendsto_const_nhds.congr' (Filter.eventually_atTop.mpr ⟨m, fun n hn =>
            (hg_zero n (Set.compl_subset_compl.mpr (hUanti hn)
              (Set.mem_compl_iff _ _ |>.mpr hxUm))).symm⟩)
    -- ENNReal version: ENNReal.ofReal (baireIntegral μ (gₙ)) → μ K
    have h_enn : Filter.Tendsto (fun n => ENNReal.ofReal (baireIntegral μ (g n)))
        Filter.atTop (nhds (μ K)) := by
      rw [show μ K = ENNReal.ofReal (μ K).toReal from
        (ENNReal.ofReal_toReal (measure_ne_top μ K)).symm]
      exact ENNReal.tendsto_ofReal h_dct
    -- iInf ≤ aₙ for each n, and aₙ → μ K, so iInf ≤ μ K
    apply ge_of_tendsto' (x := Filter.atTop)
      (f := fun n => ENNReal.ofReal (∫ x, (g n) x ∂ν))
    · rw [show μ K = ENNReal.ofReal (μ K).toReal from
        (ENNReal.ofReal_toReal (measure_ne_top μ K)).symm]
      apply ENNReal.tendsto_ofReal
      simp_rw [hbaire_eq]
      exact h_dct
    · intro n
      exact iInf₂_le_of_le (g n : α → ℝ) (g n).continuous
        (iInf_le_of_le (hg_supp n) (iInf_le_of_le (hg_one n)
          (iInf_le_of_le (fun x => (hg_range n x).1) le_rfl)))
  · -- Lower bound μ K ≤ ν K: for each continuous f ≥ 0 with f = 1 on K,
    -- ∫(baire) f dμ ≥ μ K since f ≥ 1_K.
    apply le_iInf; intro f
    apply le_iInf; intro hf_cont
    apply le_iInf; intro _
    apply le_iInf; intro hf_eq
    apply le_iInf; intro hf_nn
    have hfν : ∫ x, f x ∂ν = baireIntegral μ ⟨f, hf_cont⟩ :=
      hbaire_eq ⟨f, hf_cont⟩
    rw [hfν]
    letI hbms : MeasurableSpace α := baire α
    have hKm : @MeasurableSet α (baire α) K := by
      rw [baire_eq_generateFrom_isCompact_isGδ]
      exact MeasurableSpace.measurableSet_generateFrom ⟨hK, hGδ⟩
    rw [show μ K = ENNReal.ofReal (∫ x, Set.indicator K (1 : α → ℝ) x ∂μ)
        from by rw [integral_indicator_one hKm];
                exact (ENNReal.ofReal_toReal (measure_ne_top μ K)).symm]
    apply ENNReal.ofReal_le_ofReal
    apply integral_mono
    · exact (integrable_indicator_iff hKm).mpr ((integrable_const 1).restrict)
    · exact (baireIntegral_continuous_integrable μ ⟨f, hf_cont⟩)
    · exact fun x => by
        by_cases hxK : x ∈ K
        · simp [Set.indicator_of_mem hxK, hf_eq hxK]
        · simp only [Set.indicator_of_notMem hxK]; exact hf_nn x

/-- The Riesz Borel extension of a finite baire positive functional, trimmed to the Baire
σ-algebra, recovers the original measure. -/
private lemma trim_rieszBaireMeasure_eq
    (μ : @Measure α (baire α)) [@IsFiniteMeasure α (baire α) μ]
    (φ : NormDualSpace C(α, ℝ)) (hφ : 0 ≤ φ)
    (hφ_eq : ∀ f : C(α, ℝ), φ f = baireIntegral μ f) :
    letI : MeasurableSpace α := borel α
    letI : BorelSpace α := ⟨rfl⟩
    (rieszMeasureOfNonneg φ hφ).trim baire_le_borel = μ := by
  letI hborel_ms : MeasurableSpace α := borel α
  letI : BorelSpace α := ⟨rfl⟩
  set ν := rieszMeasureOfNonneg φ hφ
  -- Work with baire as ambient for the trimmed measure
  have hgen : baire α = MeasurableSpace.generateFrom {K : Set α | IsCompact K ∧ IsGδ K} :=
    baire_eq_generateFrom_isCompact_isGδ
  haveI : @IsFiniteMeasure α (baire α) (ν.trim baire_le_borel) :=
    isFiniteMeasure_trim baire_le_borel
  apply @MeasureTheory.ext_of_generate_finite α (baire α) _ _
    {K | IsCompact K ∧ IsGδ K} hgen isPiSystem_isCompact_isGδ
  · intro K ⟨hK, hGδ⟩
    have hKm : @MeasurableSet α (baire α) K := by
      rw [baire_eq_generateFrom_isCompact_isGδ]
      exact MeasurableSpace.measurableSet_generateFrom ⟨hK, hGδ⟩
    rw [trim_measurableSet_eq baire_le_borel hKm]
    exact_mod_cast rieszMeasure_eq_baire_of_compact_gδ μ φ hφ hφ_eq hK hGδ
  · -- ν univ = φ 1 = ∫(baire) 1 dμ = μ univ
    rw [trim_measurableSet_eq baire_le_borel (@MeasurableSet.univ α (baire α))]
    -- ∫(borel) 1 dν = φ(1) = baireIntegral μ 1 = (μ univ).toReal
    have h_int := integral_rieszMeasureOfNonneg φ hφ (ContinuousMap.const α (1 : ℝ))
    have h_ν : (ν Set.univ).toReal =
        @integral α ℝ _ _ (baire α) μ (fun _ => (1 : ℝ)) := by
      simp only [ContinuousMap.const_apply] at h_int
      rw [integral_const, smul_eq_mul, mul_one, measureReal_def] at h_int
      rw [hφ_eq] at h_int
      simp only [baireIntegral, ContinuousMap.const_apply] at h_int
      exact h_int
    have h_μ : @integral α ℝ _ _ (baire α) μ (fun _ => (1 : ℝ)) = (μ Set.univ).toReal := by
      rw [@integral_const α ℝ _ _ (baire α) μ]
      simp [measureReal_def]
    rw [← ENNReal.ofReal_toReal (measure_ne_top ν _),
        ← ENNReal.ofReal_toReal (measure_ne_top μ _), h_ν, h_μ]

/-- A regular signed Borel measure agreeing with a signed Baire measure on
all Baire measurable sets equals its signed Borel extension. -/
theorem borelExtension_unique [Nonempty α]
    (s : @SignedMeasure α (baire α))
    (σ : @SignedMeasure α (borel α))
    (hσ : @SignedMeasure.IsRegular α _ (borel α) σ)
    (h : ∀ t, @MeasurableSet α (baire α) t → σ t = s t) :
    σ = borelExtension s := by
  letI : MeasurableSpace α := borel α
  haveI : BorelSpace α := ⟨rfl⟩
  apply signedMeasureFunctional_injective_of_regular hσ (borelExtension_regular s)
  ext f
  simp only [signedMeasureFunctional_apply]
  conv_rhs => rw [show borelExtension s = rieszSignedMeasure
    ((baireSignedMeasureLinearMap s).mkContinuous _
      (baireSignedMeasureLinearMap_norm_bound s)) from rfl]
  rw [rieszSignedMeasure_integral, LinearMap.mkContinuous_apply]
  set hm := baire_le_borel (α := α)
  -- Step 1: identify s as the trim of σ on the baire σ-algebra
  have heq : s = (σ.toJordanDecomposition.posPart.trim hm).toSignedMeasure -
      (σ.toJordanDecomposition.negPart.trim hm).toSignedMeasure := by
    ext t ht
    have hbt := hm t ht
    -- RHS simplification
    have hrhs : ((σ.toJordanDecomposition.posPart.trim hm).toSignedMeasure -
        (σ.toJordanDecomposition.negPart.trim hm).toSignedMeasure) t =
        σ.toJordanDecomposition.posPart.real t -
        σ.toJordanDecomposition.negPart.real t := by
      rw [Measure.toSignedMeasure_sub_apply ht, measureReal_def, measureReal_def,
          trim_measurableSet_eq hm ht, trim_measurableSet_eq hm ht,
          ← measureReal_def, ← measureReal_def]
    rw [hrhs, ← h t ht]
    -- LHS: σ t = posPart.real t - negPart.real t
    conv_lhs =>
      rw [← SignedMeasure.toSignedMeasure_toJordanDecomposition σ]
      change (σ.toJordanDecomposition.posPart.toSignedMeasure -
              σ.toJordanDecomposition.negPart.toSignedMeasure) t
    exact Measure.toSignedMeasure_sub_apply hbt
  -- Step 2: rewrite the baire integral using the alternate decomposition of s
  set posTrim := σ.toJordanDecomposition.posPart.trim hm
  set negTrim := σ.toJordanDecomposition.negPart.trim hm
  have hbaire : baireSignedMeasureLinearMap s f =
      @integral α ℝ _ _ (baire α) posTrim (fun x => f x) -
      @integral α ℝ _ _ (baire α) negTrim (fun x => f x) := by
    -- Work in baire ambient for this subproof
    letI : MeasurableSpace α := baire α
    have hjordan :
        s.toJordanDecomposition.posPart.toSignedMeasure -
          s.toJordanDecomposition.negPart.toSignedMeasure
        = posTrim.toSignedMeasure - negTrim.toSignedMeasure := by
      rw [show s.toJordanDecomposition.posPart.toSignedMeasure -
          s.toJordanDecomposition.negPart.toSignedMeasure
          = s.toJordanDecomposition.toSignedMeasure from rfl,
        SignedMeasure.toSignedMeasure_toJordanDecomposition s, heq]
    have hadd : (s.toJordanDecomposition.posPart + negTrim).toSignedMeasure
        = (posTrim + s.toJordanDecomposition.negPart).toSignedMeasure := by
      rw [Measure.toSignedMeasure_add, Measure.toSignedMeasure_add]
      exact sub_eq_sub_iff_add_eq_add.mp hjordan
    have hmeas : s.toJordanDecomposition.posPart + negTrim =
        posTrim + s.toJordanDecomposition.negPart :=
      Measure.toSignedMeasure_eq_toSignedMeasure_iff.mp hadd
    have hint :
        ∫ x, f x ∂(s.toJordanDecomposition.posPart + negTrim) =
        ∫ x, f x ∂(posTrim + s.toJordanDecomposition.negPart) := by
      rw [hmeas]
    rw [integral_add_measure
          (baireIntegral_continuous_integrable s.toJordanDecomposition.posPart f)
          (baireIntegral_continuous_integrable negTrim f),
      integral_add_measure
          (baireIntegral_continuous_integrable posTrim f)
          (baireIntegral_continuous_integrable s.toJordanDecomposition.negPart f)] at hint
    unfold baireSignedMeasureLinearMap baireIntegral
    dsimp
    linarith
  -- Step 3: use integral_trim to convert baire integrals to borel integrals
  have hf_sm : @StronglyMeasurable α ℝ _ (baire α) f := by
    letI : MeasurableSpace α := baire α
    apply Measurable.stronglyMeasurable
    rw [measurable_iff_comap_le]
    exact le_iSup (fun g : C(α, ℝ) => MeasurableSpace.comap (⇑g) (borel ℝ)) f
  rw [hbaire, ← integral_trim hm hf_sm, ← integral_trim hm hf_sm]
  rfl

/-- The signed Borel extension agrees with the original signed Baire measure
on Baire measurable sets. -/
theorem borelExtension_apply [Nonempty α]
    (s : @SignedMeasure α (baire α))
    {t : Set α} (ht : @MeasurableSet α (baire α) t) :
    borelExtension s t = s t := by
  -- Use baire as ambient for most of the proof; switch to borel for the Riesz construction
  letI : MeasurableSpace α := baire α
  set j := s.toJordanDecomposition
  haveI := j.posPart_finite
  haveI := j.negPart_finite
  -- Build the positive/negative baire functionals ψ_pos, ψ_neg
  let ψ_pos_lm : C(α, ℝ) →ₗ[ℝ] ℝ :=
    { toFun := fun f => baireIntegral j.posPart f
      map_add' := fun f g => by
        simp only [baireIntegral, ContinuousMap.add_apply]
        exact integral_add
            (baireIntegral_continuous_integrable j.posPart f)
            (baireIntegral_continuous_integrable j.posPart g)
      map_smul' := fun c f => by
        simp only [baireIntegral, ContinuousMap.smul_apply, smul_eq_mul,
          RingHom.id_apply, integral_const_mul] }
  have hψ_pos_bd : ∀ f : C(α, ℝ), ‖ψ_pos_lm f‖ ≤ (j.posPart Set.univ).toReal * ‖f‖ :=
    fun f => by
      haveI := j.posPart_finite
      show ‖baireIntegral j.posPart f‖ ≤ (j.posPart Set.univ).toReal * ‖f‖
      unfold baireIntegral
      have h := norm_integral_le_of_norm_le_const (μ := j.posPart)
        (Filter.Eventually.of_forall (ContinuousMap.norm_coe_le_norm f))
      rwa [Measure.real, mul_comm] at h
  set ψ_pos : NormDualSpace C(α, ℝ) := ψ_pos_lm.mkContinuous _ hψ_pos_bd
  let ψ_neg_lm : C(α, ℝ) →ₗ[ℝ] ℝ :=
    { toFun := fun f => baireIntegral j.negPart f
      map_add' := fun f g => by
        simp only [baireIntegral, ContinuousMap.add_apply]
        exact integral_add
            (baireIntegral_continuous_integrable j.negPart f)
            (baireIntegral_continuous_integrable j.negPart g)
      map_smul' := fun c f => by
        simp only [baireIntegral, ContinuousMap.smul_apply, smul_eq_mul,
          RingHom.id_apply, integral_const_mul] }
  have hψ_neg_bd : ∀ f : C(α, ℝ), ‖ψ_neg_lm f‖ ≤ (j.negPart Set.univ).toReal * ‖f‖ :=
    fun f => by
      haveI := j.negPart_finite
      show ‖baireIntegral j.negPart f‖ ≤ (j.negPart Set.univ).toReal * ‖f‖
      unfold baireIntegral
      have h := norm_integral_le_of_norm_le_const (μ := j.negPart)
        (Filter.Eventually.of_forall (ContinuousMap.norm_coe_le_norm f))
      rwa [Measure.real, mul_comm] at h
  set ψ_neg : NormDualSpace C(α, ℝ) := ψ_neg_lm.mkContinuous _ hψ_neg_bd
  -- ψ_pos and ψ_neg are nonneg functionals
  have hψ_pos_nn : 0 ≤ ψ_pos := by
    change NormDualSpace.toOrderDualSpace 0 ≤ NormDualSpace.toOrderDualSpace ψ_pos
    intro f hf
    change (0 : ℝ) ≤ baireIntegral j.posPart f
    exact integral_nonneg (fun x => ContinuousMap.le_def.mp hf x)
  have hψ_neg_nn : 0 ≤ ψ_neg := by
    change NormDualSpace.toOrderDualSpace 0 ≤ NormDualSpace.toOrderDualSpace ψ_neg
    intro f hf
    change (0 : ℝ) ≤ baireIntegral j.negPart f
    exact integral_nonneg (fun x => ContinuousMap.le_def.mp hf x)
  -- ψ_pos f = baireIntegral j.posPart f (and same for ψ_neg)
  have hψ_pos_eq : ∀ f : C(α, ℝ), ψ_pos f = baireIntegral j.posPart f := fun _ => rfl
  have hψ_neg_eq : ∀ f : C(α, ℝ), ψ_neg f = baireIntegral j.negPart f := fun _ => rfl
  -- By trim_rieszBaireMeasure_eq, the Riesz measures of ψ_pos/ψ_neg trim to j.posPart/negPart
  have htrim_pos := trim_rieszBaireMeasure_eq j.posPart ψ_pos hψ_pos_nn hψ_pos_eq
  have htrim_neg := trim_rieszBaireMeasure_eq j.negPart ψ_neg hψ_neg_nn hψ_neg_eq
  -- Switch to borel ambient for the Riesz measure construction
  letI : MeasurableSpace α := borel α
  haveI : BorelSpace α := ⟨rfl⟩
  -- Build the auxiliary signed Borel measure σ_aux
  set σ_aux : SignedMeasure α :=
    (rieszMeasureOfNonneg ψ_pos hψ_pos_nn).toSignedMeasure -
    (rieszMeasureOfNonneg ψ_neg hψ_neg_nn).toSignedMeasure with hσ_aux_def
  -- σ_aux is regular
  have hσ_aux_reg : σ_aux.IsRegular :=
    SignedMeasure.IsRegular.sub
      (isRegular_toSignedMeasure inferInstance)
      (isRegular_toSignedMeasure inferInstance)
  -- σ_aux t = s t for all baire measurable t
  have hσ_aux_eq : ∀ u, @MeasurableSet α (baire α) u → σ_aux u = s u := fun u hu => by
    have hu_borel : MeasurableSet u := baire_le_borel u hu
    -- Express σ_aux u in terms of trimmed measures
    have h1 : σ_aux u =
        ((rieszMeasureOfNonneg ψ_pos hψ_pos_nn).trim baire_le_borel).real u -
        ((rieszMeasureOfNonneg ψ_neg hψ_neg_nn).trim baire_le_borel).real u := by
      simp only [hσ_aux_def, VectorMeasure.coe_sub, Pi.sub_apply,
        Measure.toSignedMeasure_apply_measurable hu_borel, measureReal_def]
      congr 1 <;> congr 1 <;>
        exact (@trim_measurableSet_eq α (baire α) (borel α) _ u baire_le_borel hu).symm
    rw [h1, htrim_pos, htrim_neg]
    conv_rhs => rw [← @SignedMeasure.toSignedMeasure_toJordanDecomposition α (baire α) s]
    letI : MeasurableSpace α := baire α
    exact (Measure.toSignedMeasure_sub_apply hu).symm
  -- By borelExtension_unique, σ_aux = borelExtension s; conclude
  rw [← borelExtension_unique s σ_aux hσ_aux_reg hσ_aux_eq]
  exact hσ_aux_eq t ht

/-- The total-variation norm of the signed Borel extension of a signed Baire
measure is bounded by the total-variation norm of the original Baire measure. -/
theorem borelExtension_norm_le [Nonempty α]
    (s : @SignedMeasure α (baire α)) :
    ‖(borelExtension s : @SignedMeasure α (borel α))‖ ≤ ‖s‖ := by
  letI : MeasurableSpace α := borel α
  haveI : BorelSpace α := ⟨rfl⟩
  rw [← norm_signedMeasureFunctional (borelExtension_regular s)]
  unfold borelExtension
  rw [signedMeasureFunctional_rieszSignedMeasure]
  exact LinearMap.mkContinuous_norm_le _ ENNReal.toReal_nonneg _

/-- The signed Borel extension of a non-negative signed Baire measure is
non-negative as a signed Borel measure. -/
theorem borelExtension_nonneg [Nonempty α]
    {s : @SignedMeasure α (baire α)} (hs : 0 ≤ s) :
    (0 : @SignedMeasure α (borel α)) ≤ borelExtension s := by
  letI : MeasurableSpace α := borel α
  haveI : BorelSpace α := ⟨rfl⟩
  unfold borelExtension
  apply rieszSignedMeasure_nonneg
  change NormDualSpace.toOrderDualSpace 0 ≤
    NormDualSpace.toOrderDualSpace ((baireSignedMeasureLinearMap s).mkContinuous _ _)
  intro f hf
  change (0 : ℝ) ≤ (baireSignedMeasureLinearMap s) f
  letI : MeasurableSpace α := baire α
  have h_neg : s.toJordanDecomposition.negPart = 0 := by
    have h : s.toJordanDecomposition.negPart.toSignedMeasure = 0 :=
      MeasureTheory.SignedMeasure.nonneg_iff_negPart_eq_zero.mp hs
    rw [← Measure.toSignedMeasure_zero] at h
    exact Measure.toSignedMeasure_eq_toSignedMeasure_iff.mp h
  change (0 : ℝ) ≤ baireIntegral s.toJordanDecomposition.posPart f -
                  baireIntegral s.toJordanDecomposition.negPart f
  rw [h_neg]
  unfold baireIntegral
  rw [integral_zero_measure, sub_zero]
  exact integral_nonneg (fun x => ContinuousMap.le_def.mp hf x)

end BaireMeasure

end
