import BanLat.Band

/-!
# Atoms and atomic vector lattices

An **atom** (or *discrete element*) of a vector lattice `X` is a positive
non-zero element `a` such that the order interval `[0, a]` is one-dimensional:
every `0 ≤ x ≤ a` is a (necessarily non-negative) scalar multiple of `a`. The
vector lattice `X` is **atomic** (or *discrete*) when it equals the band
generated by all of its atoms. In general, every Archimedean vector lattice
admits a decomposition into its **atomic part** — the band generated by all
atoms — and its **continuous part**, the disjoint complement of the atomic
part.
-/

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-! ### Atoms -/

/-- A positive non-zero element `a` of a vector lattice is an **atom** (or
*discrete element*) when every `0 ≤ x ≤ a` is a scalar multiple of `a`. -/
def IsVLAtom (a : X) : Prop :=
  0 < a ∧ ∀ x : X, 0 ≤ x → x ≤ a → ∃ c : ℝ, x = c • a

/-- An atom is strictly positive. -/
theorem IsVLAtom.pos {a : X} (h : IsVLAtom a) : 0 < a := h.1

/-- An atom is non-zero. -/
theorem IsVLAtom.ne_zero {a : X} (h : IsVLAtom a) : a ≠ 0 := h.1.ne'

private lemma smul_eq_zero_of_ne_zero_of_pos {a : X} (ha : a ≠ 0) {c : ℝ}
    (h : c • a = 0) : c = 0 := by
  by_contra hc
  apply ha
  have hcalc : c⁻¹ • (c • a) = c⁻¹ • (0 : X) := by rw [h]
  rwa [smul_smul, inv_mul_cancel₀ hc, one_smul, smul_zero] at hcalc

private lemma smul_pos_of_pos {a : X} (ha : 0 < a) {c : ℝ} (hc : 0 < c) :
    0 < c • a := by
  refine lt_of_le_of_ne (smul_nonneg hc.le ha.le) ?_
  intro hca
  exact hc.ne' (smul_eq_zero_of_ne_zero_of_pos ha.ne' hca.symm)

/-- The order interval `[0, a]` of an atom contains no two non-zero disjoint
elements. -/
theorem eq_zero_or_eq_zero_of_isVLDisjoint_of_isVLAtom
    {a : X} (h : IsVLAtom a) {x y : X}
    (hx0 : 0 ≤ x) (hxa : x ≤ a) (hy0 : 0 ≤ y) (hya : y ≤ a)
    (hxy : IsVLDisjoint x y) : x = 0 ∨ y = 0 := by
  obtain ⟨c, hc⟩ := h.2 x hx0 hxa
  obtain ⟨d, hd⟩ := h.2 y hy0 hya
  have ha_nn : 0 ≤ a := h.1.le
  have ha_ne : a ≠ 0 := h.1.ne'
  rcases lt_or_ge c 0 with hc_neg | hc_nn
  · left
    have : c • a ≤ 0 := smul_nonpos_of_nonpos_of_nonneg hc_neg.le ha_nn
    rw [← hc] at this
    exact le_antisymm this hx0
  rcases lt_or_ge d 0 with hd_neg | hd_nn
  · right
    have : d • a ≤ 0 := smul_nonpos_of_nonpos_of_nonneg hd_neg.le ha_nn
    rw [← hd] at this
    exact le_antisymm this hy0
  have hxy0 : x ⊓ y = 0 := inf_eq_zero_of_isVLDisjoint hx0 hy0 hxy
  rw [hc, hd, ← inf_smul_nonneg a c d ha_nn] at hxy0
  have hmin0 : (c ⊓ d : ℝ) = 0 := smul_eq_zero_of_ne_zero_of_pos ha_ne hxy0
  rcases le_total c d with hcd | hcd
  · left
    have hcd' : c ⊓ d = c := inf_eq_left.mpr hcd
    rw [hcd'] at hmin0
    rw [hc, hmin0, zero_smul]
  · right
    have hcd' : c ⊓ d = d := inf_eq_right.mpr hcd
    rw [hcd'] at hmin0
    rw [hd, hmin0, zero_smul]

/-- Monotonicity of scalar multiplication of a non-negative element by reals. -/
private lemma smul_le_smul_real_of_nonneg {a : X} (ha_nn : 0 ≤ a) {s t : ℝ}
    (hst : s ≤ t) : s • a ≤ t • a := by
  have hts : 0 ≤ t - s := sub_nonneg.mpr hst
  have hnn : 0 ≤ (t - s) • a := smul_nonneg hts ha_nn
  have heq : t • a = (t - s) • a + s • a := by
    rw [← add_smul]; congr 1; ring
  rw [heq]; exact le_add_of_nonneg_left hnn

/-- Under the no-disjoint-pair hypothesis, every `x ∈ [0,a]` is comparable to
every `t • a` with `t ∈ [0,1]`. -/
private lemma comparable_of_no_disjoint_in_interval
    {a : X} (ha_nn : 0 ≤ a)
    (hyp : ∀ x y : X, 0 ≤ x → x ≤ a → 0 ≤ y → y ≤ a →
      IsVLDisjoint x y → x = 0 ∨ y = 0)
    {x : X} (hx0 : 0 ≤ x) (hxa : x ≤ a) {t : ℝ} (ht0 : 0 ≤ t) (ht1 : t ≤ 1) :
    t • a ≤ x ∨ x ≤ t • a := by
  have hta_nn : 0 ≤ t • a := smul_nonneg ht0 ha_nn
  have hta_le : t • a ≤ a := by
    have := smul_le_smul_real_of_nonneg ha_nn ht1
    rwa [one_smul] at this
  set p := (x - t • a)⁺ with hp_def
  set q := (x - t • a)⁻ with hq_def
  have hp_nn : 0 ≤ p := posPart_nonneg _
  have hq_nn : 0 ≤ q := negPart_nonneg _
  have hp_le : p ≤ a := by
    rw [hp_def, posPart_def]
    exact sup_le (le_trans (sub_le_self _ hta_nn) hxa) ha_nn
  have hq_le : q ≤ a := by
    rw [hq_def, negPart_def]
    refine sup_le ?_ ha_nn
    rw [neg_sub]; exact le_trans (sub_le_self _ hx0) hta_le
  have hpq_disj : IsVLDisjoint p q := isVLDisjoint_of_inf_eq_zero
    (posPart_inf_negPart_eq_zero _)
  rcases hyp p q hp_nn hp_le hq_nn hq_le hpq_disj with hp0 | hq0
  · right
    exact sub_nonpos.mp (posPart_eq_zero.mp hp0)
  · left
    exact sub_nonneg.mp (negPart_eq_zero.mp hq0)

/-- Characterisation: a positive element `a` is an atom iff the order interval
`[0, a]` contains no two non-zero disjoint elements. -/
theorem isVLAtom_iff_no_disjoint_in_interval [IsVLArchimedean X]
    {a : X} (ha : 0 < a) :
    IsVLAtom a ↔
      ∀ x y : X, 0 ≤ x → x ≤ a → 0 ≤ y → y ≤ a →
        IsVLDisjoint x y → x = 0 ∨ y = 0 := by
  refine ⟨fun h x y hx0 hxa hy0 hya hxy =>
    eq_zero_or_eq_zero_of_isVLDisjoint_of_isVLAtom h hx0 hxa hy0 hya hxy, fun hyp => ?_⟩
  refine ⟨ha, fun x hx0 hxa => ?_⟩
  -- Set T = {t ∈ [0,1] : t•a ≤ x}; show its sup C satisfies x = C • a.
  set T : Set ℝ := {t | 0 ≤ t ∧ t ≤ 1 ∧ t • a ≤ x} with hT_def
  have hT_ne : T.Nonempty := ⟨0, ⟨le_refl 0, zero_le_one, by rw [zero_smul]; exact hx0⟩⟩
  have hT_bdd : BddAbove T := ⟨1, fun t ht => ht.2.1⟩
  set C := sSup T with hC_def
  have hC_nn : 0 ≤ C := le_csSup hT_bdd ⟨le_refl 0, zero_le_one, by rw [zero_smul]; exact hx0⟩
  have hC_le : C ≤ 1 := csSup_le hT_ne (fun t ht => ht.2.1)
  refine ⟨C, ?_⟩
  -- Step A: x ≤ C • a (from "x ≤ t•a for all t > C")
  have hx_le_Ca : x ≤ C • a := by
    have hbound : ∀ n : ℕ, 0 < n → x - C • a ≤ ((n : ℝ)⁻¹) • a := by
      intro n hn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
      rcases lt_or_ge 1 (C + (n : ℝ)⁻¹) with hgt1 | hle1
      · -- C + 1/n > 1, so x ≤ a ≤ C•a + (1/n)•a
        have h1a : x ≤ (1 : ℝ) • a := by rw [one_smul]; exact hxa
        have hsum : (1 : ℝ) • a ≤ (C + (n : ℝ)⁻¹) • a :=
          smul_le_smul_real_of_nonneg ha.le hgt1.le
        rw [add_smul] at hsum
        exact sub_le_iff_le_add'.mpr (le_trans h1a hsum)
      · have hCε_nn : 0 ≤ C + (n : ℝ)⁻¹ := by positivity
        have hnotin : C + (n : ℝ)⁻¹ ∉ T := fun hin => by
          have := le_csSup hT_bdd hin
          have hpos : (0 : ℝ) < (n : ℝ)⁻¹ := inv_pos.mpr hn_real
          linarith
        have hcomp := comparable_of_no_disjoint_in_interval ha.le hyp hx0 hxa hCε_nn hle1
        rcases hcomp with hle | hge
        · exfalso; exact hnotin ⟨hCε_nn, hle1, hle⟩
        · rw [add_smul] at hge
          exact sub_le_iff_le_add'.mpr hge
    -- Now (x - C•a)⁺ ≤ (1/n)•a for all n ≥ 1, so by Archimedean (x - C•a)⁺ = 0.
    have hposPart_bound : ∀ n : ℕ, n • (x - C • a)⁺ ≤ a := by
      intro n
      rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
      · subst hn0; rw [zero_nsmul]; exact ha.le
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
      have hb := hbound n hn_pos
      have hpp : (x - C • a)⁺ ≤ ((n : ℝ)⁻¹) • a := by
        rw [posPart_def]; exact sup_le hb (smul_nonneg (inv_nonneg.mpr hn_real.le) ha.le)
      have hns : n • (x - C • a)⁺ ≤ n • (((n : ℝ)⁻¹) • a) := nsmul_le_nsmul_right hpp n
      have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
        rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
      rwa [hrew] at hns
    have hposPart_zero : (x - C • a)⁺ = 0 :=
      IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound
    exact sub_nonpos.mp (posPart_eq_zero.mp hposPart_zero)
  -- Step B: C • a ≤ x (since for any n there's t ∈ T with t > C - 1/n)
  have hCa_le_x : C • a ≤ x := by
    have hbound : ∀ n : ℕ, 0 < n → C • a - x ≤ ((n : ℝ)⁻¹) • a := by
      intro n hn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
      obtain ⟨t, htT, htgt⟩ : ∃ t ∈ T, C - (n : ℝ)⁻¹ < t := by
        by_contra hno
        push_neg at hno
        have : C ≤ C - (n : ℝ)⁻¹ := csSup_le hT_ne hno
        have hpos : (0 : ℝ) < (n : ℝ)⁻¹ := inv_pos.mpr hn_real
        linarith
      have htle : t • a ≤ x := htT.2.2
      have hCt_le : C - t ≤ (n : ℝ)⁻¹ := by linarith
      have hsmul_le : (C - t) • a ≤ ((n : ℝ)⁻¹) • a :=
        smul_le_smul_real_of_nonneg ha.le hCt_le
      have hsplit : C • a = (C - t) • a + t • a := by
        rw [← add_smul]; congr 1; ring
      have h1 : C • a - x ≤ (C - t) • a := by
        rw [hsplit, add_sub_assoc]; exact add_le_of_nonpos_right (sub_nonpos.mpr htle)
      exact le_trans h1 hsmul_le
    have hposPart_bound : ∀ n : ℕ, n • (C • a - x)⁺ ≤ a := by
      intro n
      rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
      · subst hn0; rw [zero_nsmul]; exact ha.le
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
      have hb := hbound n hn_pos
      have hpp : (C • a - x)⁺ ≤ ((n : ℝ)⁻¹) • a := by
        rw [posPart_def]; exact sup_le hb (smul_nonneg (inv_nonneg.mpr hn_real.le) ha.le)
      have hns : n • (C • a - x)⁺ ≤ n • (((n : ℝ)⁻¹) • a) := nsmul_le_nsmul_right hpp n
      have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
        rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
      rwa [hrew] at hns
    have hposPart_zero : (C • a - x)⁺ = 0 :=
      IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound
    exact sub_nonpos.mp (posPart_eq_zero.mp hposPart_zero)
  exact le_antisymm hx_le_Ca hCa_le_x

omit [VectorLattice X] in
private lemma posPart_le_abs (x : X) : x⁺ ≤ |x| := by
  rw [← posPart_add_negPart x]; exact le_add_of_nonneg_right (negPart_nonneg x)

omit [VectorLattice X] in
private lemma negPart_le_abs (x : X) : x⁻ ≤ |x| := by
  rw [← posPart_add_negPart x]; exact le_add_of_nonneg_left (posPart_nonneg x)

/-- A positive scalar multiple of an atom is again an atom. -/
theorem IsVLAtom.smul {a : X} (h : IsVLAtom a) {c : ℝ} (hc : 0 < c) :
    IsVLAtom (c • a) := by
  refine ⟨smul_pos_of_pos h.1 hc, fun x hx0 hxca => ?_⟩
  have hcinv : 0 < c⁻¹ := inv_pos.mpr hc
  have h1 : 0 ≤ c⁻¹ • x := smul_nonneg hcinv.le hx0
  have h2 : c⁻¹ • x ≤ a := by
    have hmono := smul_le_smul_of_nonneg_left hxca hcinv.le
    rwa [smul_smul, inv_mul_cancel₀ hc.ne', one_smul] at hmono
  obtain ⟨d, hd⟩ := h.2 (c⁻¹ • x) h1 h2
  refine ⟨d, ?_⟩
  have hx_eq : x = c • (c⁻¹ • x) := by
    rw [smul_smul, mul_inv_cancel₀ hc.ne', one_smul]
  rw [hx_eq, hd, smul_smul, mul_comm, ← smul_smul]

/-- Helper: any element bounded by `k • a` (with `k ≥ 0` and `a` an atom) is a
scalar multiple of `a`. -/
private lemma exists_smul_of_le_smul_atom
    {a : X} (ha : IsVLAtom a) {y : X} (hy0 : 0 ≤ y) {k : ℝ} (hk : 0 ≤ k)
    (hyk : y ≤ k • a) : ∃ c : ℝ, y = c • a := by
  rcases eq_or_lt_of_le hk with hk0 | hkpos
  · rw [← hk0, zero_smul] at hyk
    have hy : y = 0 := le_antisymm hyk hy0
    exact ⟨0, by rw [hy, zero_smul]⟩
  · have hka : IsVLAtom (k • a) := IsVLAtom.smul ha hkpos
    obtain ⟨α, hα⟩ := hka.2 y hy0 hyk
    exact ⟨α * k, by rw [hα, smul_smul]⟩

/-- Characterisation: a positive element `a` is an atom iff its principal
ideal is the line spanned by `a`. -/
theorem isVLAtom_iff_principal_eq_span [IsVLArchimedean X] {a : X} :
    IsVLAtom a ↔
      0 < a ∧ ∀ x : X, x ∈ OrderIdeal.principal a → ∃ c : ℝ, x = c • a := by
  refine ⟨fun ha => ⟨ha.1, fun x hx => ?_⟩, fun ⟨hpos, hspan⟩ => ⟨hpos, fun x hx0 hxa => ?_⟩⟩
  · obtain ⟨c, hc_nn, hxc⟩ := OrderIdeal.mem_principal.mp hx
    rw [abs_of_nonneg ha.1.le] at hxc
    obtain ⟨α, hα⟩ := exists_smul_of_le_smul_atom ha
      (posPart_nonneg x) hc_nn (le_trans (posPart_le_abs x) hxc)
    obtain ⟨β, hβ⟩ := exists_smul_of_le_smul_atom ha
      (negPart_nonneg x) hc_nn (le_trans (negPart_le_abs x) hxc)
    refine ⟨α - β, ?_⟩
    calc x = x⁺ - x⁻ := (posPart_sub_negPart x).symm
      _ = α • a - β • a := by rw [hα, hβ]
      _ = (α - β) • a := (sub_smul α β a).symm
  · apply hspan
    rw [OrderIdeal.mem_principal]
    refine ⟨1, zero_le_one, ?_⟩
    rw [one_smul, abs_of_nonneg hx0, abs_of_nonneg hpos.le]
    exact hxa

/-- Any two atoms are either disjoint or scalar multiples of each other. -/
theorem isVLDisjoint_or_smul_of_isVLAtom [IsVLArchimedean X]
    {a b : X} (ha : IsVLAtom a) (hb : IsVLAtom b) :
    IsVLDisjoint a b ∨ ∃ c : ℝ, b = c • a := by
  by_cases hd : IsVLDisjoint a b
  · exact Or.inl hd
  refine Or.inr ?_
  have hab_nn : 0 ≤ a ⊓ b := le_inf ha.1.le hb.1.le
  have hab_ne : a ⊓ b ≠ 0 := fun habz => hd (isVLDisjoint_of_inf_eq_zero habz)
  obtain ⟨α, hα⟩ := ha.2 (a ⊓ b) hab_nn inf_le_left
  obtain ⟨β, hβ⟩ := hb.2 (a ⊓ b) hab_nn inf_le_right
  have heq : α • a = β • b := hα ▸ hβ
  have hβ_ne : β ≠ 0 := fun h0 => hab_ne (by rw [hβ, h0, zero_smul])
  refine ⟨α / β, ?_⟩
  have hcalc : (α / β) • a = β⁻¹ • (α • a) := by
    rw [div_eq_inv_mul, mul_smul]
  rw [hcalc, heq, smul_smul, inv_mul_cancel₀ hβ_ne, one_smul]

/-! ### The principal band of an atom -/

/-- For an atom `a`, a non-negative element below `c • a` is non-negatively
spanned by `a`. -/
private lemma exists_nonneg_smul_of_le_smul_atom {a : X} (ha : IsVLAtom a)
    {y : X} (hy0 : 0 ≤ y) {k : ℝ} (hk : 0 ≤ k) (hyk : y ≤ k • a) :
    ∃ c : ℝ, 0 ≤ c ∧ y = c • a := by
  obtain ⟨c, hc⟩ := exists_smul_of_le_smul_atom ha hy0 hk hyk
  rcases lt_or_ge c 0 with hcneg | hcnn
  · have hca : c • a ≤ 0 := smul_nonpos_of_nonpos_of_nonneg hcneg.le ha.1.le
    rw [← hc] at hca
    have hy : y = 0 := le_antisymm hca hy0
    exact ⟨0, le_refl 0, by rw [hy, zero_smul]⟩
  · exact ⟨c, hcnn, hc⟩

/-- For an atom `a`, a non-negative element in the principal band is a
non-negative multiple of `a`. -/
private lemma exists_nonneg_smul_of_nonneg_in_principalBand [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) {x : X} (hx0 : 0 ≤ x) (hxin : x ∈ Band.principalBand a) :
    ∃ c : ℝ, 0 ≤ c ∧ x = c • a := by
  have ha_pos := h.1
  have ha_nn : 0 ≤ a := ha_pos.le
  have ha_ne : a ≠ 0 := ha_pos.ne'
  rw [Band.mem_principalBand_iff_isLUB ha_nn hx0] at hxin
  -- Choose c_n ≥ 0 with x ⊓ n•a = c_n • a
  have hcn : ∀ n : ℕ, ∃ c : ℝ, 0 ≤ c ∧ x ⊓ (n • a) = c • a := fun n => by
    have hbound : x ⊓ (n • a) ≤ (n : ℝ) • a := by
      rw [Nat.cast_smul_eq_nsmul]; exact inf_le_right
    exact exists_nonneg_smul_of_le_smul_atom h
      (le_inf hx0 (nsmul_nonneg ha_nn n)) n.cast_nonneg hbound
  choose c hc_nn hc_eq using hcn
  -- Key: if `0 ≤ s ≤ t` (reals), then `s • a ≤ t • a`.
  have smul_mono : ∀ {s t : ℝ}, 0 ≤ s → s ≤ t → s • a ≤ t • a := by
    intro s t hs hst
    have hts : 0 ≤ t - s := sub_nonneg.mpr hst
    have hnn : 0 ≤ (t - s) • a := smul_nonneg hts ha_nn
    have heq : t • a = (t - s) • a + s • a := by
      rw [← add_smul]; congr 1; ring
    rw [heq]; exact le_add_of_nonneg_left hnn
  -- {c n} is bounded above (by Archimedean)
  have c_bound : ∃ M : ℝ, ∀ n, c n ≤ M := by
    by_contra hub
    push_neg at hub
    have step : ∀ m : ℕ, m • a ≤ x := by
      intro m
      obtain ⟨n, hn⟩ := hub (m : ℝ)
      have hm_le_cn : (m : ℝ) • a ≤ c n • a := smul_mono m.cast_nonneg hn.le
      have hcn_le_x : c n • a ≤ x := by
        have := (hc_eq n).symm.le.trans (inf_le_left (a := x) (b := n • a)); exact this
      have hmx : (m : ℝ) • a ≤ x := le_trans hm_le_cn hcn_le_x
      rwa [Nat.cast_smul_eq_nsmul] at hmx
    exact ha_ne (IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le ha_nn step)
  obtain ⟨M, hM⟩ := c_bound
  set S : Set ℝ := Set.range c
  have hS_ne : S.Nonempty := ⟨c 0, ⟨0, rfl⟩⟩
  have hS_bdd : BddAbove S := ⟨M, fun _ ⟨n, hn⟩ => hn ▸ hM n⟩
  set C := sSup S with hC_def
  have hC_ub : ∀ n, c n ≤ C := fun n => le_csSup hS_bdd ⟨n, rfl⟩
  have hC_nn : 0 ≤ C := le_trans (hc_nn 0) (hC_ub 0)
  refine ⟨C, hC_nn, ?_⟩
  -- Step A: x ≤ C • a
  have hCa_ub_set : ∀ y ∈ Set.range (fun n : ℕ => x ⊓ (n • a)), y ≤ C • a := by
    rintro _ ⟨n, rfl⟩
    change x ⊓ (n • a) ≤ C • a
    rw [hc_eq n]
    exact smul_mono (hc_nn n) (hC_ub n)
  have hx_le_Ca : x ≤ C • a := hxin.2 hCa_ub_set
  -- Step B: C • a ≤ x via Archimedean
  have hCa_diff_nn : 0 ≤ C • a - x := sub_nonneg.mpr hx_le_Ca
  have hCa_diff_bound : ∀ n : ℕ, n • (C • a - x) ≤ a := by
    intro n
    rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
    · subst hn0; rw [zero_nsmul]; exact ha_nn
    have hn_pos_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
    have hε_pos : (0 : ℝ) < (n : ℝ)⁻¹ := inv_pos.mpr hn_pos_real
    obtain ⟨_, ⟨m, rfl⟩, hcm_gt⟩ : ∃ y ∈ S, C - (n : ℝ)⁻¹ < y := by
      by_contra hno
      push_neg at hno
      have hCle : C ≤ C - (n : ℝ)⁻¹ := csSup_le hS_ne hno
      linarith
    have hCcm_lt : C - c m < (n : ℝ)⁻¹ := by linarith
    have hCcm_nn : 0 ≤ C - c m := sub_nonneg.mpr (hC_ub m)
    -- (C - c m) • a ≤ n⁻¹ • a
    have hsmul_le : (C - c m) • a ≤ (n : ℝ)⁻¹ • a := smul_mono hCcm_nn hCcm_lt.le
    -- C • a - x ≤ (C - c m) • a since c m • a ≤ x
    have hcm_le_x : c m • a ≤ x := by
      have hh : x ⊓ (m • a) ≤ x := inf_le_left
      rw [hc_eq m] at hh; exact hh
    have hCa_minus_x_le : C • a - x ≤ (C - c m) • a := by
      have hsplit : C • a = (C - c m) • a + c m • a := by
        rw [← add_smul]; congr 1; ring
      rw [hsplit, add_sub_assoc]
      exact add_le_of_nonpos_right (sub_nonpos.mpr hcm_le_x)
    -- n • (C • a - x) ≤ n • (n⁻¹ • a) = a
    have hstep : (C • a - x) ≤ (n : ℝ)⁻¹ • a := le_trans hCa_minus_x_le hsmul_le
    have hnsmul : n • (C • a - x) ≤ n • ((n : ℝ)⁻¹ • a) :=
      nsmul_le_nsmul_right hstep n
    have hrew : n • ((n : ℝ)⁻¹ • a) = a := by
      rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_pos_real.ne', one_smul]
    rwa [hrew] at hnsmul
  have hCax : C • a - x = 0 :=
    IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le hCa_diff_nn hCa_diff_bound
  exact (sub_eq_zero.mp hCax).symm

theorem principalBand_eq_smul_of_isVLAtom [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) :
    (Band.principalBand a : Set X) = {x | ∃ c : ℝ, x = c • a} := by
  apply Set.Subset.antisymm
  · -- principalBand a ⊆ ℝ • a
    intro x hx
    have hxp_in : x⁺ ∈ Band.principalBand a := (Band.principalBand a).toOrderIdeal.sup_mem
      hx (Band.principalBand a).toOrderIdeal.toSubmodule.zero_mem
    have hxn_in : x⁻ ∈ Band.principalBand a := by
      have hneg : -x ∈ Band.principalBand a :=
        (Band.principalBand a).toOrderIdeal.toSubmodule.neg_mem hx
      exact (Band.principalBand a).toOrderIdeal.sup_mem hneg
        (Band.principalBand a).toOrderIdeal.toSubmodule.zero_mem
    obtain ⟨α, _, hα⟩ := exists_nonneg_smul_of_nonneg_in_principalBand h
      (posPart_nonneg x) hxp_in
    obtain ⟨β, _, hβ⟩ := exists_nonneg_smul_of_nonneg_in_principalBand h
      (negPart_nonneg x) hxn_in
    refine ⟨α - β, ?_⟩
    calc x = x⁺ - x⁻ := (posPart_sub_negPart x).symm
      _ = α • a - β • a := by rw [hα, hβ]
      _ = (α - β) • a := (sub_smul α β a).symm
  · -- ℝ • a ⊆ principalBand a
    rintro x ⟨c, rfl⟩
    have ha_in : a ∈ Band.principalBand a :=
      Band.subset_bandGenerated {a} (Set.mem_singleton a)
    exact (Band.principalBand a).toOrderIdeal.toSubmodule.smul_mem c ha_in

/-- For an atom `a`, scalar comparison is reflected by smul. -/
private lemma smul_le_smul_iff_atom {a : X} (h : IsVLAtom a) {c d : ℝ} :
    c • a ≤ d • a ↔ c ≤ d := by
  refine ⟨fun hcd => ?_, fun hcd => smul_le_smul_real_of_nonneg h.1.le hcd⟩
  by_contra hcd'
  push_neg at hcd'
  have h1 : (c - d) • a ≤ 0 := by
    rw [sub_smul]; exact sub_nonpos.mpr hcd
  have h2 : 0 < (c - d) • a := smul_pos_of_pos h.1 (by linarith)
  exact (h2.trans_le h1).false

/-- For an atom `a` and `x ≥ 0`, there exists a non-negative `c` with `c • a ≤ x`
and `(x - c • a) ⊥ a`. -/
private lemma decomp_of_atom_nonneg [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) {x : X} (hx0 : 0 ≤ x) :
    ∃ c : ℝ, 0 ≤ c ∧ c • a ≤ x ∧ IsVLDisjoint (x - c • a) a := by
  have ha_pos := h.1
  have ha_nn : 0 ≤ a := ha_pos.le
  have ha_ne : a ≠ 0 := ha_pos.ne'
  -- Choose c_n ≥ 0 with x ⊓ n•a = c_n • a.
  have hcn : ∀ n : ℕ, ∃ c : ℝ, 0 ≤ c ∧ x ⊓ (n • a) = c • a := fun n => by
    have hbound : x ⊓ (n • a) ≤ (n : ℝ) • a := by
      rw [Nat.cast_smul_eq_nsmul]; exact inf_le_right
    exact exists_nonneg_smul_of_le_smul_atom h
      (le_inf hx0 (nsmul_nonneg ha_nn n)) n.cast_nonneg hbound
  choose c hc_nn hc_eq using hcn
  -- {c n} is bounded above (Archimedean argument).
  have c_bound : ∃ M : ℝ, ∀ n, c n ≤ M := by
    by_contra hub
    push_neg at hub
    have step : ∀ m : ℕ, m • a ≤ x := by
      intro m
      obtain ⟨n, hn⟩ := hub (m : ℝ)
      have hm_le_cn : (m : ℝ) • a ≤ c n • a :=
        smul_le_smul_real_of_nonneg ha_nn hn.le
      have hcn_le_x : c n • a ≤ x := by
        have hh : x ⊓ (n • a) ≤ x := inf_le_left
        rw [hc_eq n] at hh; exact hh
      have hmx : (m : ℝ) • a ≤ x := le_trans hm_le_cn hcn_le_x
      rwa [Nat.cast_smul_eq_nsmul] at hmx
    exact ha_ne (IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le ha_nn step)
  obtain ⟨M, hM⟩ := c_bound
  set S : Set ℝ := Set.range c with hS_def
  have hS_ne : S.Nonempty := ⟨c 0, ⟨0, rfl⟩⟩
  have hS_bdd : BddAbove S := ⟨M, fun _ ⟨n, hn⟩ => hn ▸ hM n⟩
  set C := sSup S with hC_def
  have hC_ub : ∀ n, c n ≤ C := fun n => le_csSup hS_bdd ⟨n, rfl⟩
  have hC_nn : 0 ≤ C := le_trans (hc_nn 0) (hC_ub 0)
  refine ⟨C, hC_nn, ?_, ?_⟩
  · -- C • a ≤ x via Archimedean approximation.
    have hbound : ∀ n : ℕ, 0 < n → C • a - x ≤ ((n : ℝ)⁻¹) • a := by
      intro n hn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
      obtain ⟨_, ⟨m, rfl⟩, hcm_gt⟩ : ∃ y ∈ S, C - (n : ℝ)⁻¹ < y := by
        by_contra hno
        push_neg at hno
        have hCle : C ≤ C - (n : ℝ)⁻¹ := csSup_le hS_ne hno
        linarith [inv_pos.mpr hn_real]
      have hCm_le : C - c m ≤ (n : ℝ)⁻¹ := by linarith
      have hsmul_le : (C - c m) • a ≤ ((n : ℝ)⁻¹) • a :=
        smul_le_smul_real_of_nonneg ha_nn hCm_le
      have hcm_le_x : c m • a ≤ x := by
        have hh : x ⊓ (m • a) ≤ x := inf_le_left
        rw [hc_eq m] at hh; exact hh
      have hsplit : C • a = (C - c m) • a + c m • a := by
        rw [← add_smul]; congr 1; ring
      have h1 : C • a - x ≤ (C - c m) • a := by
        rw [hsplit, add_sub_assoc]; exact add_le_of_nonpos_right (sub_nonpos.mpr hcm_le_x)
      exact le_trans h1 hsmul_le
    have hposPart_bound : ∀ n : ℕ, n • (C • a - x)⁺ ≤ a := by
      intro n
      rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
      · subst hn0; rw [zero_nsmul]; exact ha_nn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
      have hb := hbound n hn_pos
      have hpp : (C • a - x)⁺ ≤ ((n : ℝ)⁻¹) • a := by
        rw [posPart_def]; exact sup_le hb (smul_nonneg (inv_nonneg.mpr hn_real.le) ha_nn)
      have hns : n • (C • a - x)⁺ ≤ n • (((n : ℝ)⁻¹) • a) := nsmul_le_nsmul_right hpp n
      have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
        rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
      rwa [hrew] at hns
    have hposPart_zero : (C • a - x)⁺ = 0 :=
      IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound
    exact sub_nonpos.mp (posPart_eq_zero.mp hposPart_zero)
  · -- (x - C • a) ⊥ a
    have hCa_le_x : C • a ≤ x := by
      -- redo same Archimedean step (we already have it from above)
      have hbound : ∀ n : ℕ, 0 < n → C • a - x ≤ ((n : ℝ)⁻¹) • a := by
        intro n hn
        have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
        obtain ⟨_, ⟨m, rfl⟩, hcm_gt⟩ : ∃ y ∈ S, C - (n : ℝ)⁻¹ < y := by
          by_contra hno; push_neg at hno
          linarith [csSup_le hS_ne hno, inv_pos.mpr hn_real]
        have hCm_le : C - c m ≤ (n : ℝ)⁻¹ := by linarith
        have hcm_le_x : c m • a ≤ x := by
          have hh : x ⊓ (m • a) ≤ x := inf_le_left
          rw [hc_eq m] at hh; exact hh
        have hsplit : C • a = (C - c m) • a + c m • a := by
          rw [← add_smul]; congr 1; ring
        have h1 : C • a - x ≤ (C - c m) • a := by
          rw [hsplit, add_sub_assoc]; exact add_le_of_nonpos_right (sub_nonpos.mpr hcm_le_x)
        exact le_trans h1 (smul_le_smul_real_of_nonneg ha_nn hCm_le)
      have hposPart_bound : ∀ n : ℕ, n • (C • a - x)⁺ ≤ a := by
        intro n
        rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
        · subst hn0; rw [zero_nsmul]; exact ha_nn
        have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
        have hpp : (C • a - x)⁺ ≤ ((n : ℝ)⁻¹) • a := by
          rw [posPart_def]
          exact sup_le (hbound n hn_pos) (smul_nonneg (inv_nonneg.mpr hn_real.le) ha_nn)
        have hns := nsmul_le_nsmul_right hpp n
        have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
          rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
        rwa [hrew] at hns
      exact sub_nonpos.mp (posPart_eq_zero.mp
        (IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound))
    have hxCa_nn : 0 ≤ x - C • a := sub_nonneg.mpr hCa_le_x
    -- Show (x - C•a) ⊓ a = 0.
    set y := (x - C • a) ⊓ a with hy_def
    have hy_nn : 0 ≤ y := le_inf hxCa_nn ha_nn
    have hy_le : y ≤ a := inf_le_right
    have hy_le_one : y ≤ (1 : ℝ) • a := by rw [one_smul]; exact hy_le
    obtain ⟨d, hd_nn, hyd⟩ := exists_nonneg_smul_of_le_smul_atom h hy_nn zero_le_one hy_le_one
    have hd_zero : d = 0 := by
      by_contra hd_ne
      have hd_pos : 0 < d := lt_of_le_of_ne hd_nn (Ne.symm hd_ne)
      have hda_le : d • a ≤ x - C • a := by rw [← hyd]; exact inf_le_left
      have hCda_le_x : (C + d) • a ≤ x := by
        have h1 : C • a + d • a ≤ C • a + (x - C • a) := add_le_add_right hda_le (C • a)
        have h2 : C • a + (x - C • a) = x := by abel
        rw [h2] at h1
        rw [add_smul]; exact h1
      -- Pick n ∈ ℕ with C + d < n, then (C + d) • a ≤ n • a, contradicting c_n ≤ C.
      obtain ⟨n, hn⟩ : ∃ n : ℕ, C + d < n := exists_nat_gt (C + d)
      have hCdn : C + d ≤ (n : ℝ) := hn.le
      have hCda_le_na : (C + d) • a ≤ (n : ℝ) • a := smul_le_smul_real_of_nonneg ha_nn hCdn
      have hCda_le_inf : (C + d) • a ≤ x ⊓ (n • a) := by
        rw [Nat.cast_smul_eq_nsmul] at hCda_le_na
        exact le_inf hCda_le_x hCda_le_na
      rw [hc_eq n] at hCda_le_inf
      have hCdn_le_cn : C + d ≤ c n := (smul_le_smul_iff_atom h).mp hCda_le_inf
      linarith [hC_ub n]
    have hy_zero : y = 0 := by rw [hyd, hd_zero, zero_smul]
    have habs_x : |x - C • a| = x - C • a := abs_of_nonneg hxCa_nn
    have habs_a : |a| = a := abs_of_nonneg ha_nn
    change |x - C • a| ⊓ |a| = 0
    rw [habs_x, habs_a]; exact hy_zero

theorem exists_projectionBand_principalBand_of_isVLAtom [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) :
    ∃ P : ProjectionBand X, (P : Set X) = (Band.principalBand a : Set X) := by
  have ha_nn : 0 ≤ a := h.1.le
  have hpb_eq := principalBand_eq_smul_of_isVLAtom h
  -- Reformulate via projectionBand_iff_add_disjointComplement.
  have hdec : ∀ x : X, ∃ y z : X,
      y ∈ ((Band.principalBand a).toOrderIdeal : Set X)
      ∧ z ∈ disjointComplement ((Band.principalBand a).toOrderIdeal : Set X)
      ∧ x = y + z := by
    intro x
    obtain ⟨c₁, _, _, hc₁_disj⟩ := decomp_of_atom_nonneg h (posPart_nonneg x)
    obtain ⟨c₂, _, _, hc₂_disj⟩ := decomp_of_atom_nonneg h (negPart_nonneg x)
    refine ⟨(c₁ - c₂) • a, x - (c₁ - c₂) • a, ?_, ?_, by abel⟩
    · -- (c₁ - c₂) • a ∈ principalBand a
      have ha_in : a ∈ Band.principalBand a :=
        Band.subset_bandGenerated {a} (Set.mem_singleton a)
      exact (Band.principalBand a).toOrderIdeal.toSubmodule.smul_mem (c₁ - c₂) ha_in
    · -- x - (c₁ - c₂) • a is disjoint from every k • a, hence from principalBand a.
      have hdisj_a : IsVLDisjoint (x - (c₁ - c₂) • a) a := by
        have hsplit : x - (c₁ - c₂) • a = (x⁺ - c₁ • a) - (x⁻ - c₂ • a) := by
          have hps : x = x⁺ - x⁻ := (posPart_sub_negPart x).symm
          conv_lhs => rw [hps]
          rw [sub_smul]; abel
        have hd1 : (x⁺ - c₁ • a) ∈ (({a} : Set X))ᵈ := fun a' ha' => by
          rw [Set.mem_singleton_iff.mp ha']; exact hc₁_disj
        have hd2 : (x⁻ - c₂ • a) ∈ (({a} : Set X))ᵈ := fun a' ha' => by
          rw [Set.mem_singleton_iff.mp ha']; exact hc₂_disj
        have hsubmem : (x⁺ - c₁ • a) - (x⁻ - c₂ • a) ∈ (({a} : Set X))ᵈ :=
          (Band.disjointComplementOrderIdeal {a}).toSubmodule.sub_mem hd1 hd2
        rw [hsplit]
        exact hsubmem a (Set.mem_singleton a)
      intro y hy
      have hy_set : y ∈ (Band.principalBand a : Set X) := hy
      rw [hpb_eq] at hy_set
      obtain ⟨k, rfl⟩ := hy_set
      exact hdisj_a.smul_right k
  obtain ⟨P, hP⟩ := (ProjectionBand.projectionBand_iff_add_disjointComplement
    (Band.principalBand a).toOrderIdeal).mpr hdec
  exact ⟨P, hP⟩

/-! ### Atomic and continuous parts -/

variable (X) in
/-- The set of all atoms of `X`. -/
def vlAtoms : Set X := {a | IsVLAtom a}

@[simp]
theorem mem_vlAtoms {a : X} : a ∈ vlAtoms X ↔ IsVLAtom a := Iff.rfl

variable (X) in
/-- The **atomic part** of `X` is the band generated by the set of all atoms. -/
def atomicPart : Band X := Band.bandGenerated (vlAtoms X)

variable (X) in
/-- The **continuous part** of `X` is the disjoint complement of the set of
atoms — the band of vectors disjoint from every atom. -/
def continuousPart : Band X := Band.disjointComplementBand (vlAtoms X)

/-- An element belongs to the continuous part iff it is disjoint from every
atom. -/
theorem mem_continuousPart_iff {x : X} :
    x ∈ continuousPart X ↔ ∀ a : X, IsVLAtom a → IsVLDisjoint x a :=
  ⟨fun h a ha => h a ha, fun h a ha => h a ha⟩

/-- Every atom belongs to the atomic part. -/
theorem isVLAtom.mem_atomicPart {a : X} (h : IsVLAtom a) :
    a ∈ atomicPart X :=
  Band.subset_bandGenerated (vlAtoms X) h

/-- In an Archimedean vector lattice, the continuous part is the disjoint
complement of the atomic part. -/
theorem continuousPart_eq_disjointComplement_atomicPart [IsVLArchimedean X] :
    (continuousPart X : Set X) = (atomicPart X : Set X)ᵈ := by
  change ((vlAtoms X)ᵈ : Set X) = ((Band.bandGenerated (vlAtoms X) : Set X))ᵈ
  rw [← Band.disjointComplement_disjointComplement_eq_bandGenerated,
    disjointComplement_disjointComplement_disjointComplement]

/-- The atomic and continuous parts intersect only at zero. -/
theorem atomicPart_inter_continuousPart_eq_zero [IsVLArchimedean X] {x : X}
    (hx : x ∈ atomicPart X) (hx' : x ∈ continuousPart X) : x = 0 := by
  have hx'' : x ∈ ((atomicPart X : Set X))ᵈ := by
    rw [← continuousPart_eq_disjointComplement_atomicPart]; exact hx'
  have hmem : x ∈ ({0} : Set X) :=
    disjointComplement_inter_eq_zero (atomicPart X : Set X) ⟨hx, hx''⟩
  simpa using hmem

/-! ### Atomic vector lattices -/

/-- A vector lattice is **atomic** (or *discrete*) when it equals the band
generated by all of its atoms. -/
class IsAtomicVectorLattice (X : Type*) [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] : Prop where
  mem_atomicPart : ∀ x : X, x ∈ atomicPart X

/-- In an atomic vector lattice, every element belongs to the atomic part. -/
theorem mem_atomicPart_of_isAtomicVectorLattice [IsAtomicVectorLattice X]
    (x : X) : x ∈ atomicPart X :=
  IsAtomicVectorLattice.mem_atomicPart x

/-- An Archimedean vector lattice is atomic iff the only element disjoint from
every atom is zero. -/
theorem isAtomicVectorLattice_iff_continuousPart_eq_zero
    [IsVLArchimedean X] :
    IsAtomicVectorLattice X ↔ ∀ x : X, x ∈ continuousPart X → x = 0 := by
  refine ⟨fun ⟨h⟩ x hx => atomicPart_inter_continuousPart_eq_zero (h x) hx,
    fun hcont => ⟨fun x => ?_⟩⟩
  change x ∈ (atomicPart X : Set X)
  rw [(Band.eq_disjointComplement_disjointComplement (atomicPart X)).symm]
  intro y hy
  have hy_cont : y ∈ continuousPart X := by
    change y ∈ (continuousPart X : Set X)
    rw [continuousPart_eq_disjointComplement_atomicPart]
    exact hy
  rw [hcont y hy_cont]
  exact isVLDisjoint_comm.mp (isVLDisjoint_zero_left x)

/-- An Archimedean vector lattice is atomic iff every strictly positive
element dominates an atom. -/
theorem isAtomicVectorLattice_iff_forall_pos_dominates_atom
    [IsVLArchimedean X] :
    IsAtomicVectorLattice X ↔
      ∀ x : X, 0 < x → ∃ a : X, IsVLAtom a ∧ a ≤ x := by
  rw [isAtomicVectorLattice_iff_continuousPart_eq_zero]
  refine ⟨fun hcont x hx => ?_, fun hdom x hx => ?_⟩
  · -- Atomic ⟹ pos x dominates an atom.
    by_contra hno
    push_neg at hno
    have hxc : x ∈ continuousPart X := by
      intro a ha
      have hax_nn : 0 ≤ x ⊓ a := le_inf hx.le ha.1.le
      obtain ⟨c, hc_nn, hc_eq⟩ := exists_nonneg_smul_of_le_smul_atom ha hax_nn zero_le_one
        (by rw [one_smul]; exact inf_le_right)
      rcases eq_or_lt_of_le hc_nn with hc0 | hc_pos
      · have hxa : x ⊓ a = 0 := by rw [hc_eq, ← hc0, zero_smul]
        exact isVLDisjoint_of_inf_eq_zero hxa
      · exfalso
        refine hno (c • a) (IsVLAtom.smul ha hc_pos) ?_
        rw [← hc_eq]; exact inf_le_left
    exact hx.ne' (hcont x hxc)
  · -- Every pos dominates an atom ⟹ continuousPart trivial.
    by_contra hxne
    have habs_nn : 0 ≤ |x| := abs_nonneg x
    have habs_pos : 0 < |x| :=
      lt_of_le_of_ne habs_nn (fun h => hxne ((abs_eq_zero_iff_zero x).mp h.symm))
    have habs_in : |x| ∈ continuousPart X :=
      (continuousPart X).toOrderIdeal.abs_mem hx
    obtain ⟨a, ha, ha_le⟩ := hdom |x| habs_pos
    have hdisj : IsVLDisjoint (|x|) a := habs_in a ha
    have habsa : |a| = a := abs_of_nonneg ha.1.le
    have habsabsx : |(|x|)| = |x| := abs_of_nonneg habs_nn
    have hinf : (|x|) ⊓ a = 0 := by
      have hh : |(|x|)| ⊓ |a| = 0 := hdisj
      rwa [habsa, habsabsx] at hh
    apply ha.ne_zero
    have hh : a ⊓ |x| = a := inf_eq_left.mpr ha_le
    rw [inf_comm] at hinf
    rw [← hh, hinf]

/-- An Archimedean vector lattice is atomic iff its continuous part is
trivial. -/
theorem isAtomicVectorLattice_iff_continuousPart_trivial
    [IsVLArchimedean X] :
    IsAtomicVectorLattice X ↔ (continuousPart X : Set X) = {0} := by
  rw [isAtomicVectorLattice_iff_continuousPart_eq_zero]
  refine ⟨fun h => ?_, fun h x hx => ?_⟩
  · ext x
    refine ⟨h x, ?_⟩
    rintro rfl
    exact (continuousPart X).toOrderIdeal.toSubmodule.zero_mem
  · have : x ∈ ({0} : Set X) := h ▸ hx
    simpa using this
