import BanLat.Sublattice
import BanLat.Normed

/-!
# Order ideals of vector lattices

An **order ideal** (or simply *ideal*) of a vector lattice is a sublattice that is **solid**:
if `x ∈ J` and `|y| ≤ |x|` then `y ∈ J`. Equivalently, an ideal is precisely a solid
subspace. This file defines the bundled `OrderIdeal` structure extending
`VectorSublattice` and establishes the basic characterisations and properties.
-/

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-- An `OrderIdeal` of a vector lattice `X` is a vector sublattice that is **solid**:
whenever `x ∈ J` and `0 ≤ y ≤ x`, we have `y ∈ J`. -/
structure OrderIdeal (X : Type*) [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X]
    extends VectorSublattice X where
  solid' : ∀ {x y : X}, x ∈ carrier → 0 ≤ y → y ≤ x → y ∈ carrier

namespace OrderIdeal

instance : SetLike (OrderIdeal X) X where
  coe J := J.carrier
  coe_injective' p q h := by
    cases p; cases q; congr
    exact SetLike.ext' h

variable (J : OrderIdeal X)

/-- An order ideal is solid: `x ∈ J` and `0 ≤ y ≤ x` imply `y ∈ J`. -/
theorem solid {x y : X} (hx : x ∈ J) (hy0 : 0 ≤ y) (hyx : y ≤ x) :
    y ∈ J :=
  J.solid' hx hy0 hyx

/-- Every order ideal is a vector sublattice. -/
def toVectorSublattice' : VectorSublattice X :=
  J.toVectorSublattice

/-- An order ideal is closed under `⊔`. -/
theorem sup_mem {x y : X} (hx : x ∈ J) (hy : y ∈ J) :
    x ⊔ y ∈ J :=
  J.toVectorSublattice.sup_mem hx hy

/-- An order ideal is closed under `⊓`. -/
theorem inf_mem {x y : X} (hx : x ∈ J) (hy : y ∈ J) :
    x ⊓ y ∈ J :=
  J.toVectorSublattice.inf_mem hx hy

/-- An order ideal is closed under absolute value. -/
theorem abs_mem {x : X} (hx : x ∈ J) : |x| ∈ J :=
  J.toVectorSublattice.abs_mem hx

/-- If `|x| ∈ J` then `x ∈ J`. -/
theorem mem_of_abs_mem {x : X} (h : |x| ∈ J) : x ∈ J := by
  have hpos : x⁺ ∈ J := J.solid h (posPart_nonneg x) (sup_le (le_abs_self x) (abs_nonneg x))
  have hneg : x⁻ ∈ J := J.solid h (negPart_nonneg x) (sup_le (neg_le_abs x) (abs_nonneg x))
  have := J.toSubmodule.sub_mem hpos hneg
  rwa [posPart_sub_negPart] at this

/-- Solidity in terms of absolute value: `x ∈ J` and `|y| ≤ |x|` imply
`y ∈ J`. -/
theorem mem_of_abs_le_abs {x y : X} (hx : x ∈ J)
    (h : |y| ≤ |x|) : y ∈ J :=
  J.mem_of_abs_mem (J.solid (J.abs_mem hx) (abs_nonneg y) h)

/-! ### Construction from solidity -/

/-- Build an `OrderIdeal` from a submodule that is solid in the absolute-value
sense: `x ∈ M` and `|y| ≤ |x|` imply `y ∈ M`. Every solid subspace is
automatically a sublattice and an ideal. -/
def ofSolid (M : Submodule ℝ X)
    (h : ∀ x y : X, x ∈ M → |y| ≤ |x| → y ∈ M) :
    OrderIdeal X where
  toSubmodule := M
  sup_mem' := fun {x y} hx hy => by
    have hax : |x| ∈ M := h x (|x|) hx (abs_of_nonneg (abs_nonneg x)).le
    have hay : |y| ∈ M := h y (|y|) hy (abs_of_nonneg (abs_nonneg y)).le
    have hab : |x| + |y| ∈ M := M.add_mem hax hay
    apply h (|x| + |y|) (x ⊔ y) hab
    rw [abs_of_nonneg (add_nonneg (abs_nonneg x) (abs_nonneg y))]
    apply sup_le
    · exact sup_le
        (le_trans (le_abs_self x) (le_add_of_nonneg_right (abs_nonneg y)))
        (le_trans (le_abs_self y) (le_add_of_nonneg_left (abs_nonneg x)))
    · calc -(x ⊔ y) = (-x) ⊓ (-y) := neg_sup x y
        _ ≤ -x := inf_le_left
        _ ≤ |x| := neg_le_abs x
        _ ≤ |x| + |y| := le_add_of_nonneg_right (abs_nonneg y)
  solid' := fun {x y} hx hy0 hyx =>
    h x y hx (by rwa [abs_of_nonneg hy0, abs_of_nonneg (le_trans hy0 hyx)])

/-- A submodule is the carrier of an order ideal iff it is solid. -/
theorem solid_iff (M : Submodule ℝ X) :
    (∀ x y : X, x ∈ M → |y| ≤ |x| → y ∈ M) ↔
      (∀ x y : X, x ∈ M → 0 ≤ y → y ≤ x → y ∈ M) ∧
        ∀ x y : X, x ∈ M → y ∈ M → x ⊔ y ∈ M := by
  constructor
  · intro h
    exact ⟨fun _ _ hx hy0 hyx => (ofSolid M h).solid' hx hy0 hyx,
           fun _ _ hx hy => (ofSolid M h).sup_mem' hx hy⟩
  · intro ⟨hsol, hsup⟩ x y hx hle
    -- |x| ∈ M
    have habs_x : |x| ∈ M := hsup x (-x) hx (M.neg_mem hx)
    -- |y| ∈ M by solidity: 0 ≤ |y| ≤ |x| and |x| ∈ M
    have habs_y : |y| ∈ M := hsol (|x|) (|y|) habs_x (abs_nonneg y) hle
    -- y⁺ ∈ M: 0 ≤ y⁺ ≤ |y|
    have hpos : y⁺ ∈ M :=
      hsol (|y|) y⁺ habs_y (posPart_nonneg y) (sup_le (le_abs_self y) (abs_nonneg y))
    -- y⁻ ∈ M: 0 ≤ y⁻ ≤ |y|
    have hneg : y⁻ ∈ M :=
      hsol (|y|) y⁻ habs_y (negPart_nonneg y) (sup_le (neg_le_abs y) (abs_nonneg y))
    have := M.sub_mem hpos hneg
    rwa [posPart_sub_negPart] at this

/-! ### Principal ideal -/

/-- The **principal ideal** generated by `a` is the set of elements `x` with
`|x| ≤ c • |a|` for some `c ≥ 0`. -/
def principal (a : X) : OrderIdeal X where
  toSubmodule :=
    { carrier := {x : X | ∃ c : ℝ, 0 ≤ c ∧ |x| ≤ c • |a|}
      add_mem' := fun {x y} ⟨cx, hcx, hx⟩ ⟨cy, hcy, hy⟩ =>
        ⟨cx + cy, add_nonneg hcx hcy, by
          calc |x + y| ≤ |x| + |y| := abs_add_le x y
            _ ≤ cx • |a| + cy • |a| := add_le_add hx hy
            _ = (cx + cy) • |a| := (add_smul cx cy |a|).symm⟩
      zero_mem' := ⟨0, le_rfl, by simp⟩
      smul_mem' := fun r x ⟨c, hc, hx⟩ =>
        ⟨|r| * c, mul_nonneg (abs_nonneg r) hc, by
          rw [abs_smul' x r]
          calc |r| • |x| ≤ |r| • (c • |a|) :=
                smul_le_smul_of_nonneg_left hx (abs_nonneg r)
            _ = (|r| * c) • |a| := smul_smul |r| c |a|⟩ }
  sup_mem' := fun {x y} ⟨cx, hcx, hx⟩ ⟨cy, hcy, hy⟩ =>
    ⟨cx + cy, add_nonneg hcx hcy, by
      have : |x ⊔ y| ≤ |x| + |y| := by
        apply sup_le
        · exact sup_le
            (le_trans (le_abs_self x) (le_add_of_nonneg_right (abs_nonneg y)))
            (le_trans (le_abs_self y) (le_add_of_nonneg_left (abs_nonneg x)))
        · calc -(x ⊔ y) = (-x) ⊓ (-y) := neg_sup x y
            _ ≤ -x := inf_le_left
            _ ≤ |x| := neg_le_abs x
            _ ≤ |x| + |y| := le_add_of_nonneg_right (abs_nonneg y)
      calc |x ⊔ y| ≤ |x| + |y| := this
        _ ≤ cx • |a| + cy • |a| := add_le_add hx hy
        _ = (cx + cy) • |a| := (add_smul cx cy |a|).symm⟩
  solid' := fun {x y} ⟨c, hc, hx⟩ hy0 hyx =>
    ⟨c, hc, le_trans (by rw [abs_of_nonneg hy0]; exact le_trans hyx (le_abs_self x)) hx⟩

/-- Characterisation of membership in the principal ideal. -/
theorem mem_principal {a x : X} :
    x ∈ principal a ↔ ∃ c : ℝ, 0 ≤ c ∧ |x| ≤ c • |a| := Iff.rfl

/-- The generator belongs to its own principal ideal. -/
theorem self_mem_principal (a : X) : a ∈ principal a :=
  ⟨1, zero_le_one, by simp⟩

/-! ### Lattice structure -/

/-- The whole space is an order ideal. -/
instance : Top (OrderIdeal X) where
  top := {
    toVectorSublattice := ⊤
    solid' := fun _ _ _ => Submodule.mem_top
  }

/-- Every element belongs to `⊤`. -/
@[simp]
theorem mem_top {x : X} : x ∈ (⊤ : OrderIdeal X) := Submodule.mem_top

/-- The intersection of two order ideals is an order ideal. -/
def inf (J₁ J₂ : OrderIdeal X) : OrderIdeal X where
  toSubmodule := J₁.toSubmodule ⊓ J₂.toSubmodule
  sup_mem' := fun ⟨hx1, hx2⟩ ⟨hy1, hy2⟩ =>
    ⟨J₁.sup_mem hx1 hy1, J₂.sup_mem hx2 hy2⟩
  solid' := fun ⟨hx1, hx2⟩ hy0 hyx =>
    ⟨J₁.solid hx1 hy0 hyx, J₂.solid hx2 hy0 hyx⟩

/-- The coercion to `Submodule ℝ X` is injective. -/
theorem toSubmodule_injective :
    Function.Injective
      (fun J : OrderIdeal X => J.toSubmodule) := by
  intro p q h
  cases p; cases q; congr
  exact VectorSublattice.toSubmodule_injective h

/-! ### Gauge norm on the principal ideal -/

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-- The **gauge norm** (or order-unit norm) of `x` with respect to `a` is
`inf {c ≥ 0 | |x| ≤ c • |a|}`. For `x` in the principal ideal of `a`, this
is finite and defines a lattice seminorm; it is a norm precisely when the
ambient space is Archimedean. -/
noncomputable def gaugeNorm (a x : X) : ℝ :=
  sInf {c : ℝ | 0 ≤ c ∧ |x| ≤ c • |a|}

variable (a : X)

/-- The gauge norm is non-negative. -/
theorem gaugeNorm_nonneg (x : X) : 0 ≤ gaugeNorm a x := by
  unfold gaugeNorm
  by_cases h : {c : ℝ | 0 ≤ c ∧ |x| ≤ c • |a|}.Nonempty
  · exact le_csInf h fun _ ⟨hc, _⟩ => hc
  · rw [Set.not_nonempty_iff_eq_empty.mp h, Real.sInf_empty]

/-- The gauge norm of zero is zero. -/
theorem gaugeNorm_zero : gaugeNorm a 0 = 0 := by
  apply le_antisymm
  · exact csInf_le ⟨0, fun _ ⟨hd, _⟩ => hd⟩ ⟨le_rfl, by simp⟩
  · exact gaugeNorm_nonneg a 0

/-- The gauge norm is symmetric. -/
theorem gaugeNorm_neg (x : X) :
    gaugeNorm a (-x) = gaugeNorm a x := by
  simp only [gaugeNorm, abs_neg]

/-- Triangle inequality for the gauge norm. -/
private theorem gaugeNorm_bddBelow (x : X) :
    BddBelow {c : ℝ | 0 ≤ c ∧ |x| ≤ c • |a|} :=
  ⟨0, fun _ ⟨hc, _⟩ => hc⟩

theorem gaugeNorm_add_le {x y : X} (hx : x ∈ principal a) (hy : y ∈ principal a) :
    gaugeNorm a (x + y) ≤ gaugeNorm a x + gaugeNorm a y := by
  -- Step 1: For fixed cy ∈ S_y, gaugeNorm(x+y) - cy ≤ gaugeNorm(x)
  have step1 : ∀ cy, cy ∈ {c : ℝ | 0 ≤ c ∧ |y| ≤ c • |a|} →
      gaugeNorm a (x + y) - cy ≤ gaugeNorm a x := by
    intro cy ⟨hcy, hcy_le⟩
    apply le_csInf hx
    intro cx ⟨hcx, hcx_le⟩
    have : cx + cy ∈ {c : ℝ | 0 ≤ c ∧ |x + y| ≤ c • |a|} :=
      ⟨add_nonneg hcx hcy, le_trans (abs_add_le x y)
        (by rw [add_smul]; exact add_le_add hcx_le hcy_le)⟩
    exact sub_le_iff_le_add.mpr (csInf_le (gaugeNorm_bddBelow a (x + y)) this)
  -- Step 2: gaugeNorm(x+y) - gaugeNorm(x) ≤ gaugeNorm(y)
  have step2 : gaugeNorm a (x + y) - gaugeNorm a x ≤ gaugeNorm a y :=
    le_csInf hy (fun cy hcy => by linarith [step1 cy hcy])
  linarith

/-- Absolute homogeneity of the gauge norm. -/
private theorem gaugeNorm_div_mem {r : ℝ} (hr_pos : 0 < |r|) {x : X} {c : ℝ}
    (hc : 0 ≤ c) (hle : |r| • |x| ≤ c • |a|) :
    c / |r| ∈ {c : ℝ | 0 ≤ c ∧ |x| ≤ c • |a|} := by
  refine ⟨div_nonneg hc hr_pos.le, ?_⟩
  have := smul_le_smul_of_nonneg_left hle (inv_nonneg.mpr hr_pos.le)
  rw [smul_smul, inv_mul_cancel₀ (ne_of_gt hr_pos), one_smul, smul_smul] at this
  rwa [div_eq_inv_mul]

theorem gaugeNorm_smul (r : ℝ) (x : X) :
    gaugeNorm a (r • x) = |r| * gaugeNorm a x := by
  by_cases hr : r = 0
  · simp [hr, gaugeNorm_zero]
  · have hr_pos : (0 : ℝ) < |r| := abs_pos.mpr hr
    -- S_x nonempty ↔ S_{rx} nonempty (when r ≠ 0)
    by_cases hne : {c : ℝ | 0 ≤ c ∧ |x| ≤ c • |a|}.Nonempty
    · apply le_antisymm
      · -- ≤: gaugeNorm(rx)/|r| ≤ gaugeNorm(x), then multiply
        suffices h : gaugeNorm a (r • x) / |r| ≤ gaugeNorm a x from
          (div_le_iff₀ hr_pos).mp h |>.trans (le_of_eq (mul_comm _ _))
        apply le_csInf hne
        intro d ⟨hd, hle⟩
        rw [div_le_iff₀ hr_pos]
        exact (csInf_le (gaugeNorm_bddBelow a (r • x))
          ⟨mul_nonneg hr_pos.le hd, by
            rw [abs_smul' x r, mul_smul]
            exact smul_le_smul_of_nonneg_left hle hr_pos.le⟩).trans (le_of_eq (mul_comm _ _))
      · -- ≥: for any c in S_{rx}, c/|r| ∈ S_x, so gaugeNorm(x) ≤ c/|r|
        obtain ⟨d, hd, hle⟩ := hne
        have hne_rx : {c : ℝ | 0 ≤ c ∧ |r • x| ≤ c • |a|}.Nonempty :=
          ⟨|r| * d, mul_nonneg hr_pos.le hd, by
            rw [abs_smul' x r, mul_smul]
            exact smul_le_smul_of_nonneg_left hle hr_pos.le⟩
        apply le_csInf hne_rx
        intro c ⟨hc, hle'⟩
        calc |r| * gaugeNorm a x
            ≤ |r| * (c / |r|) :=
              mul_le_mul_of_nonneg_left
                (csInf_le (gaugeNorm_bddBelow a x) (gaugeNorm_div_mem a hr_pos hc
                  (by rwa [abs_smul' x r] at hle'))) hr_pos.le
          _ = c := by field_simp
    · -- Both S_x and S_{rx} empty: both sides are 0
      have hne2 : ¬{c : ℝ | 0 ≤ c ∧ |r • x| ≤ c • |a|}.Nonempty := by
        intro ⟨c, hc, hle⟩
        exact hne ⟨c / |r|, gaugeNorm_div_mem a hr_pos hc
          (by rwa [abs_smul' x r] at hle)⟩
      simp only [gaugeNorm, Set.not_nonempty_iff_eq_empty.mp hne,
        Set.not_nonempty_iff_eq_empty.mp hne2, Real.sInf_empty, mul_zero]

/-- The gauge norm controls the absolute value: `|x| ≤ ‖x‖_a • |a|` for
`x` in the principal ideal. -/
theorem abs_le_gaugeNorm_smul_abs [IsVLArchimedean X] {x : X}
    (hx : x ∈ principal a) : |x| ≤ gaugeNorm a x • |a| := by
  suffices h : (|x| - gaugeNorm a x • |a|)⁺ = 0 by
    have := le_posPart (|x| - gaugeNorm a x • |a|)
    rw [h] at this; exact sub_nonpos.mp this
  apply IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (y := |a|) (posPart_nonneg _)
  intro n
  by_cases hn : n = 0
  · simp [hn]
  · have hne : {c : ℝ | 0 ≤ c ∧ |x| ≤ c • |a|}.Nonempty := hx
    have hn_pos : (0 : ℝ) < ↑n := Nat.cast_pos.mpr (Nat.pos_of_ne_zero hn)
    have hlt : gaugeNorm a x < gaugeNorm a x + 1 / ↑n :=
      lt_add_of_pos_right _ (div_pos one_pos hn_pos)
    obtain ⟨c, ⟨_, hcle⟩, hc_lt⟩ := exists_lt_of_csInf_lt hne hlt
    have hstep : |x| - gaugeNorm a x • |a| ≤ (1 / (↑n : ℝ)) • |a| := by
      calc |x| - gaugeNorm a x • |a|
          ≤ c • |a| - gaugeNorm a x • |a| := sub_le_sub_right hcle _
        _ = (c - gaugeNorm a x) • |a| := (sub_smul c (gaugeNorm a x) |a|).symm
        _ ≤ (1 / ↑n) • |a| :=
            smul_le_smul_of_nonneg_right (by linarith) (abs_nonneg a)
    have hpos_le : (|x| - gaugeNorm a x • |a|)⁺ ≤ (1 / (↑n : ℝ)) • |a| :=
      sup_le hstep (smul_nonneg (div_nonneg one_pos.le hn_pos.le) (abs_nonneg a))
    calc n • (|x| - gaugeNorm a x • |a|)⁺
        ≤ n • ((1 / (↑n : ℝ)) • |a|) :=
          nsmul_le_nsmul hpos_le (smul_nonneg (div_nonneg one_pos.le hn_pos.le)
            (abs_nonneg a)) le_rfl
      _ = ((↑n : ℝ) * (1 / ↑n)) • |a| := by
          rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul]
      _ = |a| := by rw [mul_one_div_cancel (ne_of_gt hn_pos), one_smul]

/-- Any admissible constant bounds the gauge norm from above. -/
theorem gaugeNorm_le_of_abs_le {x : X} {c : ℝ} (hc : 0 ≤ c)
    (h : |x| ≤ c • |a|) : gaugeNorm a x ≤ c :=
  csInf_le ⟨0, fun _ ⟨hd, _⟩ => hd⟩ ⟨hc, h⟩

/-- The gauge norm is monotone with respect to `|·|`: the solid-norm
property. -/
theorem gaugeNorm_mono_abs {x y : X} (hy : y ∈ principal a) (h : |x| ≤ |y|) :
    gaugeNorm a x ≤ gaugeNorm a y := by
  -- S_y ⊆ S_x, so sInf S_x ≤ sInf S_y
  apply le_csInf hy
  intro c ⟨hc, hle⟩
  exact csInf_le (gaugeNorm_bddBelow a x) ⟨hc, le_trans h hle⟩

/-- In an Archimedean vector lattice the gauge norm is definite:
`gaugeNorm a x = 0 ↔ x = 0` for `x` in the principal ideal of `a`. -/
theorem gaugeNorm_eq_zero_iff [IsVLArchimedean X] {x : X}
    (hx : x ∈ principal a) : gaugeNorm a x = 0 ↔ x = 0 := by
  constructor
  · intro h
    have := abs_le_gaugeNorm_smul_abs a hx
    rw [h, zero_smul] at this
    exact (abs_eq_zero_iff_zero x).mp (le_antisymm this (abs_nonneg x))
  · intro h; rw [h]; exact gaugeNorm_zero a

/-- The closed unit ball of the gauge norm is the order interval
`[-|a|, |a|]`. -/
theorem gaugeNorm_le_one_iff [IsVLArchimedean X] {x : X} (hx : x ∈ principal a) :
    gaugeNorm a x ≤ 1 ↔ |x| ≤ |a| := by
  constructor
  · intro h
    calc |x| ≤ gaugeNorm a x • |a| := abs_le_gaugeNorm_smul_abs a hx
      _ ≤ 1 • |a| := smul_le_smul_of_nonneg_right h (abs_nonneg a)
      _ = |a| := one_smul ℝ |a|
  · intro h
    exact gaugeNorm_le_of_abs_le a one_pos.le (by rwa [one_smul])

/-- If `0 ≤ e ≤ u` then `‖·‖_u ≤ ‖·‖_e` on `I_e`. -/
theorem gaugeNorm_anti {e u : X} (he : 0 ≤ e) (heu : e ≤ u)
    {x : X} (hx : x ∈ principal e) : gaugeNorm u x ≤ gaugeNorm e x := by
  -- S_e ⊆ S_u (since |e| = e ≤ u = |u|, so c • |e| ≤ c • |u|)
  apply le_csInf hx
  intro c ⟨hc, hle⟩
  apply csInf_le (gaugeNorm_bddBelow u x)
  exact ⟨hc, le_trans hle (smul_le_smul_of_nonneg_left
    (by rwa [abs_of_nonneg he, abs_of_nonneg (le_trans he heu)]) hc)⟩

/-! ### Normed vector lattice structure on the principal ideal -/

/-- The underlying submodule of the principal ideal. -/
abbrev principalSubmodule (a : X) : Submodule ℝ X :=
  (principal a).toSubmodule

/-- The gauge norm as a `Norm` instance on the principal ideal. -/
noncomputable instance instNormPrincipal (a : X) :
    Norm ↥(principalSubmodule a) where
  norm x := gaugeNorm a x.1

/-- The principal ideal inherits a lattice structure from `X`. -/
noncomputable instance instLatticePrincipal (a : X) :
    Lattice ↥(principalSubmodule a) where
  sup x y := ⟨x.1 ⊔ y.1, (principal a).sup_mem x.2 y.2⟩
  inf x y := ⟨x.1 ⊓ y.1, (principal a).inf_mem x.2 y.2⟩
  le_sup_left := fun x y => show x.1 ≤ x.1 ⊔ y.1 from le_sup_left
  le_sup_right := fun x y => show y.1 ≤ x.1 ⊔ y.1 from le_sup_right
  sup_le := fun x y z h1 h2 => show x.1 ⊔ y.1 ≤ z.1 from sup_le h1 h2
  inf_le_left := fun x y => show x.1 ⊓ y.1 ≤ x.1 from inf_le_left
  inf_le_right := fun x y => show x.1 ⊓ y.1 ≤ y.1 from inf_le_right
  le_inf := fun x y z h1 h2 => show x.1 ≤ y.1 ⊓ z.1 from le_inf h1 h2

/-- The principal ideal is an ordered additive monoid. -/
instance instIsOrderedAddMonoidPrincipal (a : X) :
    @IsOrderedAddMonoid ↥(principalSubmodule a)
      inferInstance (instLatticePrincipal a).toPartialOrder where
  add_le_add_left := fun x y (h : x.1 ≤ y.1) z =>
    show x.1 + z.1 ≤ y.1 + z.1 from add_le_add_left h _

/-- In an Archimedean vector lattice, the principal ideal `I_a` with the gauge
norm is a normed additive commutative group. -/
noncomputable def principalNormedAddCommGroup [IsVLArchimedean X]
    (a : X) (_ha : a ≠ 0) :
    NormedAddCommGroup ↥(principalSubmodule a) :=
  NormedAddCommGroup.ofCore (𝕜 := ℝ) {
    toCore := {
      norm_nonneg := fun x => gaugeNorm_nonneg a x.1
      norm_smul := fun r x => gaugeNorm_smul a r x.1
      norm_triangle := fun x y => gaugeNorm_add_le a x.2 y.2
    }
    norm_eq_zero_iff := fun x => (gaugeNorm_eq_zero_iff a x.2).trans
      ⟨fun h => Subtype.ext h, fun h => congr_arg Subtype.val h⟩
  }

/-- In an Archimedean vector lattice, the principal ideal `I_a` with the gauge
norm admits a `VectorLattice` structure. -/
noncomputable def principalVectorLattice (a : X) :
    @VectorLattice ↥(principalSubmodule a) inferInstance
      (instLatticePrincipal a)
      (@instIsOrderedAddMonoidPrincipal X _ _ _ _ a) where
  toModule := (principalSubmodule a).module
  smul_le_smul_of_nonneg_left := by
    intro c hc x y hxy
    change c • x.1 ≤ c • y.1
    exact smul_le_smul_of_nonneg_left hxy hc

/-- In an Archimedean vector lattice, the principal ideal `I_a` equipped with
the gauge norm is a normed vector lattice. -/
noncomputable def principalNormedVectorLattice [IsVLArchimedean X]
    (a : X) (ha : a ≠ 0) :
    @NormedVectorLattice ↥(principalSubmodule a)
      (principalNormedAddCommGroup a ha)
      (instLatticePrincipal a)
      (@instIsOrderedAddMonoidPrincipal X _ _ _ _ a) := by
  letI := principalNormedAddCommGroup a ha
  exact {
    toVectorLattice := principalVectorLattice a
    solid := by
      intro x y h
      change gaugeNorm a x.1 ≤ gaugeNorm a y.1
      exact gaugeNorm_mono_abs a y.2 h
    norm_smul := by
      intro r x
      change gaugeNorm a (r • x.1) = ‖r‖ * gaugeNorm a x.1
      rw [gaugeNorm_smul a r x.1, Real.norm_eq_abs]
  }

end OrderIdeal
