import BanLat.Dual
import BanLat.Substructures.Sublattice

/-!
# Formal lattice-linear expressions

A **formal lattice-linear expression** in `n` variables is a syntactic term built
from the variables `t₁, …, tₙ` by means of addition, real scalar multiplication,
and the binary lattice operations `⊔` and `⊓`. Such an expression can be
evaluated at any `n`-tuple of vectors in a vector lattice, yielding an element
of that lattice.

Two key facts are recorded at the end of the file: the sublattice generated by a
finite tuple consists exactly of the evaluations of lattice-linear expressions
in those variables, and an expression that vanishes identically on `ℝ` vanishes
identically on every vector lattice.
-/

/-- A formal lattice-linear expression in `n` variables, built from the
variables by addition, real scalar multiplication, and the binary lattice
operations `⊔` and `⊓`. -/
inductive LLexpr (n : ℕ) where
  | zero : LLexpr n
  | var : Fin n → LLexpr n
  | add : LLexpr n → LLexpr n → LLexpr n
  | smul : ℝ → LLexpr n → LLexpr n
  | sup : LLexpr n → LLexpr n → LLexpr n
  | inf : LLexpr n → LLexpr n → LLexpr n

namespace LLexpr

variable {n : ℕ}

/-- Evaluation of a formal lattice-linear expression at an `n`-tuple of vectors
in a vector lattice. -/
def eval {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] (x : Fin n → X) : LLexpr n → X
  | .zero => 0
  | .var i => x i
  | .add e₁ e₂ => eval x e₁ + eval x e₂
  | .smul r e => r • eval x e
  | .sup e₁ e₂ => eval x e₁ ⊔ eval x e₂
  | .inf e₁ e₂ => eval x e₁ ⊓ eval x e₂

section Evaluation

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

@[simp] theorem eval_zero (x : Fin n → X) : eval x .zero = 0 := rfl

@[simp] theorem eval_var (x : Fin n → X) (i : Fin n) : eval x (.var i) = x i :=
  rfl

@[simp] theorem eval_add (x : Fin n → X) (e₁ e₂ : LLexpr n) :
    eval x (.add e₁ e₂) = eval x e₁ + eval x e₂ := rfl

@[simp] theorem eval_smul (x : Fin n → X) (r : ℝ) (e : LLexpr n) :
    eval x (.smul r e) = r • eval x e := rfl

@[simp] theorem eval_sup (x : Fin n → X) (e₁ e₂ : LLexpr n) :
    eval x (.sup e₁ e₂) = eval x e₁ ⊔ eval x e₂ := rfl

@[simp] theorem eval_inf (x : Fin n → X) (e₁ e₂ : LLexpr n) :
    eval x (.inf e₁ e₂) = eval x e₁ ⊓ eval x e₂ := rfl

end Evaluation

/-! ### Lattice-linear combinations of a tuple -/

section Combinations

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-- The set of lattice-linear combinations of a tuple `x : Fin n → X`, i.e. the
image of `LLexpr n` under evaluation at `x`. -/
def combinations (x : Fin n → X) : Set X :=
  Set.range (eval x)

/-- The sublattice generated by the image of a tuple `x : Fin n → X` coincides
with the set of lattice-linear combinations of `x`. -/
theorem generated_range_eq_combinations (x : Fin n → X) :
    (VectorSublattice.generated (Set.range x) : Set X)
      = combinations x := sorry

/-- The sublattice generated by a set `s` coincides with the union, over all
natural numbers `n` and all `n`-tuples `x` with values in `s`, of the sets of
lattice-linear combinations of `x`. -/
theorem generated_eq_iUnion_combinations (s : Set X) :
    (VectorSublattice.generated s : Set X)
      = ⋃ (n : ℕ) (x : Fin n → s), combinations ((↑) ∘ x) := sorry

end Combinations

/-! ### Yudin's theorem -/

/-- A formal lattice-linear expression *vanishes* on a vector lattice `X` if its
evaluation is zero for every substitution by vectors of `X`. -/
def Vanishes (X : Type*) [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] (e : LLexpr n) : Prop :=
  ∀ x : Fin n → X, eval x e = 0

/-- Yudin's theorem: a formal lattice-linear expression that vanishes on `ℝ`
vanishes on every vector lattice. -/
theorem vanishes_of_vanishes_real (e : LLexpr n) (h : Vanishes ℝ e)
    (X : Type*) [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] : Vanishes X e := sorry

end LLexpr
