import BanLat.Dual
import BanLat.Substructures.Sublattice
import Mathlib.Analysis.Convex.Topology
import Mathlib.Analysis.LocallyConvex.Separation

/-!
# Formal lattice-linear expressions

A **formal lattice-linear expression** in `n` variables is a syntactic term built
from the variables `t₁, …, tₙ` by means of addition, real scalar multiplication,
and the binary lattice operations `⊔` and `⊓`. Such an expression can be
evaluated at any `n`-tuple of vectors in a vector lattice, yielding an element
of that lattice.

Two key facts are recorded at the end of the file: the sublattice generated by a
finite tuple consists exactly of the evaluations of lattice-linear expressions
in those variables, and an expression that vanishes identically on `ℝ` vanishes
identically on every vector lattice.
-/

/-- A formal lattice-linear expression in `n` variables, built from the
variables by addition, real scalar multiplication, and the binary lattice
operations `⊔` and `⊓`. -/
inductive LLexpr (n : ℕ) where
  | zero : LLexpr n
  | var : Fin n → LLexpr n
  | add : LLexpr n → LLexpr n → LLexpr n
  | smul : ℝ → LLexpr n → LLexpr n
  | sup : LLexpr n → LLexpr n → LLexpr n
  | inf : LLexpr n → LLexpr n → LLexpr n

namespace LLexpr

open scoped BigOperators

variable {n : ℕ}

/-- Evaluation of a formal lattice-linear expression at an `n`-tuple of vectors
in a vector lattice. -/
def eval {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] (x : Fin n → X) : LLexpr n → X
  | .zero => 0
  | .var i => x i
  | .add e₁ e₂ => eval x e₁ + eval x e₂
  | .smul r e => r • eval x e
  | .sup e₁ e₂ => eval x e₁ ⊔ eval x e₂
  | .inf e₁ e₂ => eval x e₁ ⊓ eval x e₂

/-- Rename the variables of an expression along `f`.

This is used when two expressions depending on different finite tuples are
viewed as expressions in one concatenated tuple, and when a tuple is compressed
to the distinct elements in its range. -/
def reindexExpr {m n : ℕ} (f : Fin n → Fin m) : LLexpr n → LLexpr m
  | .zero => .zero
  | .var i => .var (f i)
  | .add e₁ e₂ => .add (reindexExpr f e₁) (reindexExpr f e₂)
  | .smul r e => .smul r (reindexExpr f e)
  | .sup e₁ e₂ => .sup (reindexExpr f e₁) (reindexExpr f e₂)
  | .inf e₁ e₂ => .inf (reindexExpr f e₁) (reindexExpr f e₂)

section Evaluation

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

@[simp] theorem eval_zero (x : Fin n → X) : eval x .zero = 0 := rfl

@[simp] theorem eval_var (x : Fin n → X) (i : Fin n) : eval x (.var i) = x i :=
  rfl

@[simp] theorem eval_add (x : Fin n → X) (e₁ e₂ : LLexpr n) :
    eval x (.add e₁ e₂) = eval x e₁ + eval x e₂ := rfl

@[simp] theorem eval_smul (x : Fin n → X) (r : ℝ) (e : LLexpr n) :
    eval x (.smul r e) = r • eval x e := rfl

@[simp] theorem eval_sup (x : Fin n → X) (e₁ e₂ : LLexpr n) :
    eval x (.sup e₁ e₂) = eval x e₁ ⊔ eval x e₂ := rfl

@[simp] theorem eval_inf (x : Fin n → X) (e₁ e₂ : LLexpr n) :
    eval x (.inf e₁ e₂) = eval x e₁ ⊓ eval x e₂ := rfl

@[simp]
theorem eval_reindexExpr {m n : ℕ} (x : Fin m → X)
    (f : Fin n → Fin m) (e : LLexpr n) :
    eval x (reindexExpr f e) = eval (fun i => x (f i)) e := by
  induction e <;> simp [reindexExpr, *]

/-- Any finite family factors through an injective finite family listing its range.

The map `f` records, for each original index, the corresponding index in the
range listing. This is useful when reducing an arbitrary finite tuple to a
tuple of distinct entries. -/
theorem exists_injective_reindex {ι : Type*} {n : ℕ} (a : Fin n → ι) :
    ∃ (m : ℕ) (b : Fin m → ι) (_ : Function.Injective b) (f : Fin n → Fin m),
      ∀ i, b (f i) = a i := by
  classical
  let s : Set ι := Set.range a
  have hs : s.Finite := Set.finite_range a
  letI : Fintype s := hs.fintype
  let e : s ≃ Fin (Fintype.card s) := Fintype.equivFin s
  refine ⟨Fintype.card s, fun j => (e.symm j).1, ?_, fun i => e ⟨a i, ⟨i, rfl⟩⟩, ?_⟩
  · intro i j hij
    exact e.symm.injective (Subtype.ext hij)
  · intro i
    simp

/-- A vector lattice homomorphism commutes with evaluation of lattice-linear expressions. -/
theorem map_eval {Y Z : Type*}
    [AddCommGroup Y] [Lattice Y] [IsOrderedAddMonoid Y] [VectorLattice Y]
    [AddCommGroup Z] [Lattice Z] [IsOrderedAddMonoid Z] [VectorLattice Z]
    (T : VecLatHom Y Z) (y : Fin n → Y) (e : LLexpr n) :
    T (eval y e) = eval (fun i => T (y i)) e := by
  induction e with
  | zero => simp [eval]
  | var i => simp [eval]
  | add e₁ e₂ h₁ h₂ => simp [eval, h₁, h₂]
  | smul r e h => simp [eval, h]
  | sup e₁ e₂ h₁ h₂ => simp [eval, h₁, h₂, map_sup]
  | inf e₁ e₂ h₁ h₂ => simp [eval, h₁, h₂, map_inf]

end Evaluation

/-! ### Lattice-linear combinations of a tuple -/

section Combinations

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-- The set of lattice-linear combinations of a tuple `x : Fin n → X`, i.e. the
image of `LLexpr n` under evaluation at `x`. -/
def combinations (x : Fin n → X) : Set X :=
  Set.range (eval x)

/-- The sublattice generated by the image of a tuple `x : Fin n → X` coincides
with the set of lattice-linear combinations of `x`. -/
theorem generated_range_eq_combinations (x : Fin n → X) :
    (VectorSublattice.generated (Set.range x) : Set X)
      = combinations x := by
  let Y : VectorSublattice X :=
    { toSubmodule :=
        { carrier := combinations x
          zero_mem' := ⟨.zero, rfl⟩
          add_mem' := by
            rintro _ _ ⟨e₁, rfl⟩ ⟨e₂, rfl⟩
            exact ⟨.add e₁ e₂, rfl⟩
          smul_mem' := by
            rintro r _ ⟨e, rfl⟩
            exact ⟨.smul r e, rfl⟩ }
      sup_mem' := by
        rintro _ _ ⟨e₁, rfl⟩ ⟨e₂, rfl⟩
        exact ⟨.sup e₁ e₂, rfl⟩ }
  refine Set.Subset.antisymm ?_ ?_
  · change (VectorSublattice.generated (Set.range x) : Set X) ⊆ (Y : Set X)
    exact VectorSublattice.generated_le (Y := Y) (by
      rintro _ ⟨i, rfl⟩
      exact ⟨.var i, rfl⟩)
  · rintro _ ⟨e, rfl⟩
    induction e with
    | zero =>
        exact (VectorSublattice.generated (Set.range x)).toSubmodule.zero_mem
    | var i =>
        exact VectorSublattice.subset_generated (Set.range x) ⟨i, rfl⟩
    | add e₁ e₂ he₁ he₂ =>
        exact (VectorSublattice.generated (Set.range x)).toSubmodule.add_mem he₁ he₂
    | smul r e he =>
        exact (VectorSublattice.generated (Set.range x)).toSubmodule.smul_mem r he
    | sup e₁ e₂ he₁ he₂ =>
        exact (VectorSublattice.generated (Set.range x)).sup_mem he₁ he₂
    | inf e₁ e₂ he₁ he₂ =>
        exact (VectorSublattice.generated (Set.range x)).inf_mem he₁ he₂

/-- The sublattice generated by a set `s` coincides with the union, over all
natural numbers `n` and all `n`-tuples `x` with values in `s`, of the sets of
lattice-linear combinations of `x`. -/
theorem generated_eq_iUnion_combinations (s : Set X) :
    (VectorSublattice.generated s : Set X)
      = ⋃ (n : ℕ) (x : Fin n → s), combinations ((↑) ∘ x) := by
  let U : Set X := ⋃ (n : ℕ) (x : Fin n → s), combinations ((↑) ∘ x)
  let Y : VectorSublattice X :=
    { toSubmodule :=
        { carrier := U
          zero_mem' := by
            refine Set.mem_iUnion.mpr ⟨0, ?_⟩
            refine Set.mem_iUnion.mpr ⟨Fin.elim0, ?_⟩
            exact ⟨.zero, rfl⟩
          add_mem' := by
            rintro _ _ hx hy
            simp only [U, Set.mem_iUnion] at hx hy ⊢
            obtain ⟨m, x, e₁, rfl⟩ := hx
            obtain ⟨k, y, e₂, rfl⟩ := hy
            refine ⟨m + k, Fin.append x y, .add (reindexExpr (Fin.castAdd k) e₁)
              (reindexExpr (Fin.natAdd m) e₂), ?_⟩
            simp [Function.comp_def]
          smul_mem' := by
            rintro r _ hx
            simp only [U, Set.mem_iUnion] at hx ⊢
            obtain ⟨m, x, e, rfl⟩ := hx
            exact ⟨m, x, .smul r e, rfl⟩ }
      sup_mem' := by
        rintro _ _ hx hy
        simp only [U, Set.mem_iUnion] at hx hy ⊢
        obtain ⟨m, x, e₁, rfl⟩ := hx
        obtain ⟨k, y, e₂, rfl⟩ := hy
        refine ⟨m + k, Fin.append x y, .sup (reindexExpr (Fin.castAdd k) e₁)
          (reindexExpr (Fin.natAdd m) e₂), ?_⟩
        simp [Function.comp_def] }
  have hsY : s ⊆ Y := by
    intro a ha
    change a ∈ U
    refine Set.mem_iUnion.mpr ⟨1, ?_⟩
    refine Set.mem_iUnion.mpr ⟨(fun _ : Fin 1 => ⟨a, ha⟩), ?_⟩
    exact ⟨.var 0, rfl⟩
  refine Set.Subset.antisymm ?_ ?_
  · exact VectorSublattice.generated_le hsY
  · intro a ha
    simp only [Set.mem_iUnion] at ha
    obtain ⟨m, x, hx⟩ := ha
    have hxgen :
        a ∈ (VectorSublattice.generated (Set.range ((Subtype.val : s → X) ∘ x)) : Set X) := by
      rwa [generated_range_eq_combinations ((Subtype.val : s → X) ∘ x)]
    exact VectorSublattice.generated_le (Y := VectorSublattice.generated s) (fun y hy => by
      obtain ⟨i, rfl⟩ := hy
      exact VectorSublattice.subset_generated s (x i).2) hxgen

end Combinations

/-! ### Yudin's theorem -/

/-- A formal lattice-linear expression *vanishes* on a vector lattice `X` if its
evaluation is zero for every substitution by vectors of `X`. -/
def Vanishes (X : Type*) [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] (e : LLexpr n) : Prop :=
  ∀ x : Fin n → X, eval x e = 0

/-- Evaluate a finitely supported linear form, encoded by its coefficient
function `a`, on an `n`-tuple of vectors. -/
private def linEval {X : Type*} [AddCommGroup X] [Module ℝ X]
    (a : Fin n → ℝ) (x : Fin n → X) : X :=
  ∑ i, a i • x i

@[simp] private theorem linEval_zero {X : Type*} [AddCommGroup X] [Module ℝ X]
    (x : Fin n → X) :
    linEval (fun _ : Fin n => 0) x = 0 := by
  simp [linEval]

@[simp] private theorem linEval_single {X : Type*} [AddCommGroup X] [Module ℝ X]
    (i : Fin n) (x : Fin n → X) :
    linEval (Pi.single i 1) x = x i := by
  simp [linEval]

@[simp] private theorem linEval_add {X : Type*} [AddCommGroup X] [Module ℝ X]
    (a b : Fin n → ℝ) (x : Fin n → X) :
    linEval (fun i => a i + b i) x = linEval a x + linEval b x := by
  simp [linEval, add_smul, Finset.sum_add_distrib]

@[simp] private theorem linEval_smul {X : Type*} [AddCommGroup X] [Module ℝ X]
    (r : ℝ) (a : Fin n → ℝ) (x : Fin n → X) :
    linEval (fun i => r * a i) x = r • linEval a x := by
  simp [linEval, Finset.smul_sum, smul_smul]

private theorem sup'_add_right {ι X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] (s : Finset ι) (hs : s.Nonempty) (f : ι → X) (a : X) :
    s.sup' hs f + a = s.sup' hs (fun i => f i + a) :=
  map_finset_sup' (OrderIso.addRight a) hs f

private theorem add_left_sup' {ι X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] (s : Finset ι) (hs : s.Nonempty) (f : ι → X) (a : X) :
    a + s.sup' hs f = s.sup' hs (fun i => a + f i) :=
  map_finset_sup' (OrderIso.addLeft a) hs f

/-- Non-negative scalar multiplication as a `SupHom`. This packages
`nonneg_smul_sup` so finite suprema can be mapped through scalar
multiplication by `map_finset_sup'`. -/
private def smulSupHom {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (r : ℝ) (hr : 0 ≤ r) : SupHom X X where
  toFun := fun z => r • z
  map_sup' := fun a b => nonneg_smul_sup a b r hr

/-- A finite nonempty supremum of linear forms.

An element of `SupLin n` represents the map
`x ↦ sup { linEval a x | a ∈ forms }`. The finiteness and nonemptiness keep the
construction elementary and avoid ambient completeness assumptions. -/
private structure SupLin (n : ℕ) where
  forms : Finset (Fin n → ℝ)
  nonempty : forms.Nonempty

namespace SupLin

/-- Evaluate a finite supremum of linear forms on a tuple in a vector lattice. -/
private noncomputable def eval {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (A : SupLin n) (x : Fin n → X) : X :=
  A.forms.sup' A.nonempty fun a => linEval a x

private noncomputable def singleton (a : Fin n → ℝ) : SupLin n :=
  { forms := {a}
    nonempty := Finset.singleton_nonempty a }

@[simp] private theorem eval_singleton {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (a : Fin n → ℝ) (x : Fin n → X) :
    (singleton a).eval x = linEval a x := by
  simp [eval, singleton]

private noncomputable def add (A B : SupLin n) : SupLin n := by
  classical
  exact
    { forms := A.forms.image₂ (fun a b i => a i + b i) B.forms
      nonempty := A.nonempty.image₂ B.nonempty }

@[simp] private theorem eval_add {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (A B : SupLin n) (x : Fin n → X) :
    (A.add B).eval x = A.eval x + B.eval x := by
  classical
  unfold eval add
  rw [Finset.sup'_image₂_left]
  simp only [linEval_add]
  simp_rw [← add_left_sup' B.forms B.nonempty (fun b => linEval b x)]
  rw [← sup'_add_right A.forms A.nonempty (fun a => linEval a x)]

private noncomputable def sup (A B : SupLin n) : SupLin n :=
  { forms := A.forms ∪ B.forms
    nonempty := A.nonempty.mono Finset.subset_union_left }

@[simp] private theorem eval_sup {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (A B : SupLin n) (x : Fin n → X) :
    (A.sup B).eval x = A.eval x ⊔ B.eval x := by
  classical
  unfold eval sup
  rw [Finset.sup'_union]

private noncomputable def smul (r : ℝ) (A : SupLin n) : SupLin n := by
  classical
  exact
    { forms := A.forms.image fun a i => r * a i
      nonempty := A.nonempty.image _ }

@[simp] private theorem eval_smul {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {r : ℝ} (hr : 0 ≤ r)
    (A : SupLin n) (x : Fin n → X) :
    (A.smul r).eval x = r • A.eval x := by
  classical
  unfold eval smul
  rw [Finset.sup'_image]
  change A.forms.sup' A.nonempty (fun a => linEval (fun i => r * a i) x) =
    r • A.forms.sup' A.nonempty (fun a => linEval a x)
  simp_rw [linEval_smul]
  exact (map_finset_sup' (smulSupHom r hr) A.nonempty (fun a => linEval a x)).symm

private theorem continuousLinearMap_apply_eq_linEval (f : StrongDual ℝ (Fin n → ℝ))
    (a : Fin n → ℝ) :
    f a = linEval a (fun i => f (Pi.single i (1 : ℝ) : Fin n → ℝ)) := by
  classical
  have ha : a = ∑ i, a i • (Pi.single i (1 : ℝ) : Fin n → ℝ) := by
    funext j
    simp [Pi.single_apply, Finset.sum_apply]
  calc
    f a = f (∑ i, a i • (Pi.single i (1 : ℝ) : Fin n → ℝ)) := by rw [← ha]
    _ = ∑ i, f (a i • (Pi.single i (1 : ℝ) : Fin n → ℝ)) := by rw [map_sum]
    _ = ∑ i, a i * f (Pi.single i (1 : ℝ) : Fin n → ℝ) := by simp
    _ = linEval a (fun i => f (Pi.single i (1 : ℝ) : Fin n → ℝ)) := by
      simp [linEval, smul_eq_mul]

/-- A finite-dimensional support-function criterion for membership in the
convex hull of `S`.

If every real linear functional takes value on `p` no larger than its supremum
over `S`, then `p` belongs to the convex hull of `S`. The proof is by separating
`p` from the closed convex hull of the finite set `S`. -/
private theorem mem_convexHull_of_forall_le_sup (p : Fin n → ℝ)
    (S : Finset (Fin n → ℝ)) (hS : S.Nonempty)
    (h : ∀ r : Fin n → ℝ, linEval p r ≤ S.sup' hS (fun q => linEval q r)) :
    p ∈ convexHull ℝ (S : Set (Fin n → ℝ)) := by
  classical
  by_contra hp
  obtain ⟨f, u, hfp, hsep⟩ := geometric_hahn_banach_point_closed
    (convex_convexHull ℝ (S : Set (Fin n → ℝ))) S.finite_toSet.isClosed_convexHull hp
  let c : Fin n → ℝ := fun i => f (Pi.single i (1 : ℝ) : Fin n → ℝ)
  let r : Fin n → ℝ := fun i => -c i
  have hf_eval : ∀ a : Fin n → ℝ, f a = linEval a c := fun a =>
    continuousLinearMap_apply_eq_linEval f a
  have hsup_lt : S.sup' hS (fun q => linEval q r) < linEval p r := by
    rw [Finset.sup'_lt_iff]
    intro q hq
    have hqconv : q ∈ convexHull ℝ (S : Set (Fin n → ℝ)) :=
      subset_convexHull ℝ (S : Set (Fin n → ℝ)) hq
    have hqsep := hsep q hqconv
    have : -f q < -f p := by
      simpa using neg_lt_neg (hfp.trans hqsep)
    have hq_eval : linEval q r = -f q := by
      rw [hf_eval q]
      simp [linEval, r, c, Finset.sum_neg_distrib]
    have hp_eval : linEval p r = -f p := by
      rw [hf_eval p]
      simp [linEval, r, c, Finset.sum_neg_distrib]
    simpa [hq_eval, hp_eval] using this
  exact (not_lt_of_ge (h r)) hsup_lt

/-- If the coefficient vector `p` is a convex combination of the coefficient
vectors in `B`, then its linear evaluation is bounded by the supremum `B.eval`.

This is the vector-lattice step: the scalar convex-combination coefficients are
non-negative, so the pointwise order bound can be summed. -/
private theorem linEval_le_sup_of_mem_convexHull {X : Type*} [AddCommGroup X]
    [Lattice X] [IsOrderedAddMonoid X] [VectorLattice X] (B : SupLin n)
    {p : Fin n → ℝ} (hp : p ∈ convexHull ℝ (B.forms : Set (Fin n → ℝ)))
    (x : Fin n → X) :
    linEval p x ≤ B.eval x := by
  classical
  rw [Finset.mem_convexHull'] at hp
  obtain ⟨w, hw_nonneg, hw_sum, hw_eq⟩ := hp
  have hcoord : ∀ i, p i = ∑ q ∈ B.forms, w q * q i := by
    intro i
    have hfun := congrFun hw_eq i
    simpa [Pi.smul_apply] using hfun.symm
  calc
    linEval p x = ∑ i, (∑ q ∈ B.forms, w q * q i) • x i := by
      simp [linEval, hcoord]
    _ = ∑ i, ∑ q ∈ B.forms, (w q * q i) • x i := by
      refine Finset.sum_congr rfl ?_
      intro i _
      rw [Finset.sum_smul]
    _ = ∑ q ∈ B.forms, ∑ i, (w q * q i) • x i := by
      rw [Finset.sum_comm]
    _ = ∑ q ∈ B.forms, w q • linEval q x := by
      refine Finset.sum_congr rfl ?_
      intro q _
      simp [linEval, Finset.smul_sum, mul_smul]
    _ ≤ ∑ q ∈ B.forms, w q • B.eval x := by
      refine Finset.sum_le_sum fun q hq => ?_
      exact smul_le_smul_of_nonneg_left
        (Finset.le_sup' (fun q => linEval q x) hq) (hw_nonneg q hq)
    _ = B.eval x := by
      rw [← Finset.sum_smul, hw_sum, one_smul]

private theorem eval_le_of_forall_real_le {X : Type*} [AddCommGroup X]
    [Lattice X] [IsOrderedAddMonoid X] [VectorLattice X] (A B : SupLin n)
    (h : ∀ r : Fin n → ℝ, A.eval r ≤ B.eval r) (x : Fin n → X) :
    A.eval x ≤ B.eval x := by
  classical
  unfold eval
  refine Finset.sup'_le A.nonempty (fun p => linEval p x) fun p hp => ?_
  exact linEval_le_sup_of_mem_convexHull B
    (mem_convexHull_of_forall_le_sup p B.forms B.nonempty fun r =>
      (Finset.le_sup' (fun a => linEval a r) hp).trans (h r)) x

private theorem eval_eq_of_forall_real_eq {X : Type*} [AddCommGroup X]
    [Lattice X] [IsOrderedAddMonoid X] [VectorLattice X] (A B : SupLin n)
    (h : ∀ r : Fin n → ℝ, A.eval r = B.eval r) (x : Fin n → X) :
    A.eval x = B.eval x :=
  le_antisymm (eval_le_of_forall_real_le A B (fun r => (h r).le) x)
    (eval_le_of_forall_real_le B A (fun r => (h r).ge) x)

end SupLin

/-- A signed normal form `pos - neg`, where both sides are finite suprema of
linear forms. -/
private structure NormalForm (n : ℕ) where
  pos : SupLin n
  neg : SupLin n

namespace NormalForm

private noncomputable def eval {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (N : NormalForm n) (x : Fin n → X) : X :=
  N.pos.eval x - N.neg.eval x

private noncomputable def zero : NormalForm n :=
  { pos := SupLin.singleton (fun _ : Fin n => 0)
    neg := SupLin.singleton (fun _ : Fin n => 0) }

private noncomputable def var (i : Fin n) : NormalForm n :=
  { pos := SupLin.singleton (Pi.single i (1 : ℝ) : Fin n → ℝ)
    neg := SupLin.singleton (fun _ : Fin n => 0) }

private noncomputable def add (N M : NormalForm n) : NormalForm n :=
  { pos := N.pos.add M.pos
    neg := N.neg.add M.neg }

private noncomputable def negate (N : NormalForm n) : NormalForm n :=
  { pos := N.neg
    neg := N.pos }

private noncomputable def smul (r : ℝ) (N : NormalForm n) : NormalForm n :=
  if 0 ≤ r then
    { pos := N.pos.smul r
      neg := N.neg.smul r }
  else
    { pos := N.neg.smul (-r)
      neg := N.pos.smul (-r) }

private noncomputable def sup (N M : NormalForm n) : NormalForm n :=
  { pos := (N.pos.add M.neg).sup (M.pos.add N.neg)
    neg := N.neg.add M.neg }

private noncomputable def inf (N M : NormalForm n) : NormalForm n :=
  negate (sup (negate N) (negate M))

private theorem sup_sub_identity {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] (a b c d : X) :
    ((a + d) ⊔ (b + c)) - (c + d) = (a - c) ⊔ (b - d) := by
  have h : ((a - c) ⊔ (b - d)) + (c + d) = (a + d) ⊔ (b + c) := by
    rw [sup_add]
    congr 1 <;> abel
  rw [← h]
  abel

@[simp] private theorem eval_zero {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (x : Fin n → X) :
    (zero : NormalForm n).eval x = 0 := by
  simp [eval, zero]

@[simp] private theorem eval_var {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (i : Fin n) (x : Fin n → X) :
    (var i).eval x = x i := by
  simp [eval, var]

@[simp] private theorem eval_add {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (N M : NormalForm n) (x : Fin n → X) :
    (add N M).eval x = N.eval x + M.eval x := by
  simp [eval, add]
  abel

@[simp] private theorem eval_negate {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (N : NormalForm n)
    (x : Fin n → X) :
    (negate N).eval x = -N.eval x := by
  simp [eval, negate]

@[simp] private theorem eval_smul {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (r : ℝ) (N : NormalForm n)
    (x : Fin n → X) :
    (smul r N).eval x = r • N.eval x := by
  by_cases hr : 0 ≤ r
  · simp [smul, hr, eval, smul_sub]
  · have hneg : 0 ≤ -r := by linarith
    simp [smul, hr, hneg, eval, smul_sub]
    abel

@[simp] private theorem eval_sup {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (N M : NormalForm n) (x : Fin n → X) :
    (sup N M).eval x = N.eval x ⊔ M.eval x := by
  simp [eval, sup, sup_sub_identity]

@[simp] private theorem eval_inf {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (N M : NormalForm n) (x : Fin n → X) :
    (inf N M).eval x = N.eval x ⊓ M.eval x := by
  simp [inf, neg_sup]

end NormalForm

/-- Convert an arbitrary lattice-linear expression into a signed supremum of
linear forms, preserving evaluation in every vector lattice. -/
private noncomputable def normalForm : LLexpr n → NormalForm n
  | .zero => NormalForm.zero
  | .var i => NormalForm.var i
  | .add e₁ e₂ => NormalForm.add (normalForm e₁) (normalForm e₂)
  | .smul r e => NormalForm.smul r (normalForm e)
  | .sup e₁ e₂ => NormalForm.sup (normalForm e₁) (normalForm e₂)
  | .inf e₁ e₂ => NormalForm.inf (normalForm e₁) (normalForm e₂)

@[simp] private theorem normalForm_eval {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (x : Fin n → X) (e : LLexpr n) :
    (normalForm e).eval x = eval x e := by
  induction e <;> simp [normalForm, *]

/-- Yudin's theorem: a formal lattice-linear expression that vanishes on `ℝ`
vanishes on every vector lattice. -/
theorem vanishes_of_vanishes_real (e : LLexpr n) (h : Vanishes ℝ e)
    (X : Type*) [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] : Vanishes X e := by
  intro x
  have hreal : ∀ r : Fin n → ℝ, (normalForm e).pos.eval r = (normalForm e).neg.eval r := by
    intro r
    have hr := h r
    rw [← normalForm_eval r e, NormalForm.eval] at hr
    exact sub_eq_zero.mp hr
  have hx := SupLin.eval_eq_of_forall_real_eq (normalForm e).pos (normalForm e).neg hreal x
  rw [← normalForm_eval x e, NormalForm.eval, hx, sub_self]

end LLexpr
