import BanLat.Substructures.Ideal
import Mathlib.Order.Filter.AtTopBot.Basic

/-!
# AM-spaces

This file introduces AM-spaces and AM-spaces with unit. An `AMSpace` is a
Banach lattice whose norm satisfies the AM-axiom on disjoint elements. An
`AMSpaceWithUnit` is an AM-space equipped with a strong order unit whose gauge
norm agrees with the original norm.

The main structural result is that every principal ideal, equipped with its
gauge norm, is an AM-space with unit; conversely, in an AM-space with unit,
the unit generates the whole space as a principal ideal.
-/

/-! ### AM-spaces -/

/-- An **AM-space** is a Banach lattice whose norm satisfies the AM-axiom on
disjoint elements: if `x ⊓ y = 0`, then `‖x + y‖ = max ‖x‖ ‖y‖`. The
positivity of `x` and `y` is automatic from `x ⊓ y = 0`. -/
class AMSpace (X : Type*) [NormedAddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] extends BanachLattice X where
  norm_add_eq_max_of_inf_eq_zero {x y : X} (hxy : x ⊓ y = 0) :
    ‖x + y‖ = max ‖x‖ ‖y‖

namespace AMSpace

variable {X : Type*} [NormedAddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [AMSpace X]

/-- For disjoint elements in an AM-space, the norm of the supremum is the
maximum of the norms. -/
theorem norm_sup_eq_max_of_inf_eq_zero {x y : X} (hxy : x ⊓ y = 0) :
    ‖x ⊔ y‖ = max ‖x‖ ‖y‖ := by
  have hx : 0 ≤ x := by
    rw [← hxy]
    exact inf_le_left
  have hy : 0 ≤ y := by
    rw [← hxy]
    exact inf_le_right
  have hadd : x + y = x ⊔ y := by
    calc
      x + y = x + (y - x)⁺ := by
        rw [← sub_inf_eq_posPart y x, inf_comm, hxy, sub_zero]
      _ = x ⊔ y := (sup_eq_add_posPart x y).symm
  rw [← hadd]
  exact AMSpace.norm_add_eq_max_of_inf_eq_zero hxy

end AMSpace

/-! ### AM-spaces with unit -/

/-- An **AM-space with unit** is an AM-space equipped with a strong order unit
whose gauge norm agrees with the original norm. -/
class AMSpaceWithUnit (X : Type*) [NormedAddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] extends AMSpace X where
  unit : X
  strongOrderUnit_unit : StrongOrderUnit unit
  norm_eq_gaugeNorm : ∀ x : X, ‖x‖ = OrderIdeal.gaugeNorm unit x

namespace AMSpaceWithUnit

variable {X : Type*} [NormedAddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [AMSpaceWithUnit X]

/-- The distinguished unit of an AM-space with unit is non-negative. -/
theorem unit_nonneg : 0 ≤ (AMSpaceWithUnit.unit : X) :=
  AMSpaceWithUnit.strongOrderUnit_unit.1

/-- In an AM-space with unit, the distinguished unit is a strong order unit. -/
theorem strongOrderUnit_unit' : StrongOrderUnit (AMSpaceWithUnit.unit : X) :=
  AMSpaceWithUnit.strongOrderUnit_unit

/-- In an AM-space with unit, the principal ideal generated by the unit is the
whole space. -/
theorem principal_unit_eq_top : OrderIdeal.principal (AMSpaceWithUnit.unit : X) = ⊤ :=
  (OrderIdeal.strongOrderUnit_iff_principal_eq_top.mp
    AMSpaceWithUnit.strongOrderUnit_unit).2

end AMSpaceWithUnit

/-!
Draft material about principal ideals as AM-spaces with unit is intentionally
omitted from the active file until the supporting infrastructure is
ready (uniformly complete vector lattices).
-/
