import BanLat.OrderContinuous.MeyerNieberg
import BanLat.OrderContinuous.Decomposition

/-!
# Ando's theorem

A Banach lattice has an order continuous norm iff every norm-closed order
ideal is a band; in that case every norm-closed ideal is a projection band.
-/

variable {X : Type*} [NormedAddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]

namespace BanachLattice

variable [BanachLattice X]

/-- In an order continuous Banach lattice, every norm-closed order ideal is
a band. -/
theorem band_of_isClosed_orderIdeal [IsOrderContinuousNorm X]
    (J : OrderIdeal X) (hcl : IsClosed (J : Set X)) :
    ∃ B : Band X, (B : Set X) = (J : Set X) := by
  refine ⟨Band.ofPosDirectedSSupMem J ?_, rfl⟩
  intro S hS hpos hdir hne x hx
  -- Index by `↥S` as a directed nonempty preorder.
  haveI : Nonempty ↥S := hne.to_subtype
  haveI : IsDirected ↥S (· ≤ ·) := ⟨fun a b => by
    obtain ⟨c, hc, hac, hbc⟩ := hdir a.val a.2 b.val b.2
    exact ⟨⟨c, hc⟩, hac, hbc⟩⟩
  -- Antitone net `u s = x - s`, nonneg, with `IsGLB 0` since `x = sup S`.
  let u : ↥S → X := fun s => x - s.val
  have hu_anti : Antitone u := fun a b h =>
    sub_le_sub_left (show a.val ≤ b.val from h) x
  have hu_nn : ∀ s, 0 ≤ u s := fun s => sub_nonneg.mpr (hx.1 s.2)
  have hu_glb : IsGLB (Set.range u) 0 := by
    refine ⟨?_, ?_⟩
    · rintro _ ⟨s, rfl⟩; exact hu_nn s
    · intro w hw
      have hub : ∀ y ∈ S, y ≤ x - w := fun y hy =>
        le_sub_comm.mp (hw ⟨⟨y, hy⟩, rfl⟩)
      have h := hx.2 hub
      rwa [le_sub_iff_add_le, add_comm, add_le_iff_nonpos_left] at h
  -- Order continuity gives `u → 0`, hence the inclusion `s ↦ s.val → x`.
  have htend := IsOrderContinuousNorm.tendsto_of_antitone_isGLB_zero
    hu_anti hu_nn hu_glb
  have hval_tend : Filter.Tendsto (fun s : ↥S => s.val) Filter.atTop (nhds x) := by
    have h1 : Filter.Tendsto (fun s : ↥S => x - u s) Filter.atTop (nhds (x - 0)) :=
      tendsto_const_nhds.sub htend
    simpa [u, sub_sub_cancel] using h1
  -- `J` is closed and contains each `s.val`, so `x ∈ J`.
  exact hcl.mem_of_tendsto hval_tend (Filter.Eventually.of_forall (fun s => hS s.2))

/-- A Banach lattice in which every norm-closed ideal is a band has an order
continuous norm.

**Proof sketch.** By Meyer-Nieberg's characterisation, it suffices to show
that every order-bounded disjoint sequence converges to zero in norm. Given
such a sequence `(uₙ) ⊆ [0, w]`, let `J` be the closed ideal generated by
`{uₙ}`. By hypothesis `J` is a band; the closed-sum lemma makes `J + Jᵈ`
closed, hence a band, hence `(J + Jᵈ)ᵈᵈ = J + Jᵈ`; combined with `(J + Jᵈ)ᵈ ⊆
Jᵈ ∩ Jᵈᵈ = {0}` one gets `J + Jᵈ = X`, so `J` is a projection band. Denoting
by `P` the band projection, `Pw ∈ J` is norm-approximated by `v` with `|v| ≤
∑_{k ≤ N} λ_k uₖ`; for `n > N`, disjointness gives `v ⊥ uₙ` and `uₙ ≤ |Pw −
v|`, whence `‖uₙ‖ < ε`.

The remaining `sorry` is this inner argument; it requires a "closed ideal
generated by a set" construction together with a density/approximation lemma
for principal-style generating elements, neither of which is yet in the
library. -/
theorem isOrderContinuousNorm_of_isClosed_ideal_isBand
    (h : ∀ J : OrderIdeal X, IsClosed (J : Set X) →
      ∃ B : Band X, (B : Set X) = (J : Set X)) :
    IsOrderContinuousNorm X := by
  -- Reduce to Meyer-Nieberg: every order-bounded disjoint sequence in a
  -- Banach lattice must converge to zero in norm.
  refine isOrderContinuousNorm_of_disjoint_tendsto_zero (fun {u} hd hbd => ?_)
  sorry

/-- **Ando's theorem**: a Banach lattice has an order continuous norm iff
every norm-closed ideal is a band. -/
theorem isOrderContinuousNorm_iff_isClosed_ideal_isBand :
    IsOrderContinuousNorm X ↔
      (∀ J : OrderIdeal X, IsClosed (J : Set X) →
        ∃ B : Band X, (B : Set X) = (J : Set X)) :=
  ⟨fun _ => band_of_isClosed_orderIdeal,
   fun h => isOrderContinuousNorm_of_isClosed_ideal_isBand h⟩

/-- In an order continuous Banach lattice, every norm-closed ideal is a
projection band. -/
theorem projectionBand_of_isClosed_orderIdeal
    [IsOrderContinuousNorm X]
    (J : OrderIdeal X) (hcl : IsClosed (J : Set X)) :
    ∃ P : ProjectionBand X, (P : Set X) = (J : Set X) := by
  -- `Jᵈ` as an order ideal.
  let Jd : OrderIdeal X := (Band.disjointComplement ((J : Set X))).toOrderIdeal
  have hJd_set : ((Jd : Set X)) = ((J : Set X))ᵈ := rfl
  -- `Jᵈ` is closed.
  have hJd_cl : IsClosed ((Jd : Set X)) := by
    rw [hJd_set]; exact isClosed_disjointComplement ((J : Set X))
  -- `J + Jᵈ` is a closed order ideal.
  have hSum_cl : IsClosed ((OrderIdeal.sum J Jd : OrderIdeal X) : Set X) :=
    (ClosedOrderIdeal.sup
      { toOrderIdeal := J, isClosed' := hcl }
      { toOrderIdeal := Jd, isClosed' := hJd_cl }).isClosed'
  -- ...hence a band (under OCN).
  obtain ⟨BSum, hBSum⟩ :=
    band_of_isClosed_orderIdeal (OrderIdeal.sum J Jd) hSum_cl
  -- Show `J + Jᵈ = X` by chasing disjoint complements.
  -- Inclusions: `J ⊆ J + Jᵈ` and `Jᵈ ⊆ J + Jᵈ` (at the set level).
  have hJ_sub : ((J : Set X)) ⊆ ((OrderIdeal.sum J Jd : OrderIdeal X) : Set X) := by
    intro a ha
    exact Submodule.mem_sup.mpr ⟨a, ha, 0, Submodule.zero_mem _, by simp⟩
  have hJd_sub : ((Jd : Set X)) ⊆ ((OrderIdeal.sum J Jd : OrderIdeal X) : Set X) := by
    intro a ha
    exact Submodule.mem_sup.mpr ⟨0, Submodule.zero_mem _, a, ha, by simp⟩
  -- `(J + Jᵈ)ᵈ ⊆ {0}`.
  have hSumd_zero : (((OrderIdeal.sum J Jd : OrderIdeal X) : Set X))ᵈ ⊆ ({0} : Set X) := by
    intro x hx
    have hxJ : x ∈ ((J : Set X))ᵈ := disjointComplement_anti hJ_sub hx
    have hxJd : x ∈ ((Jd : Set X))ᵈ := disjointComplement_anti hJd_sub hx
    rw [hJd_set] at hxJd
    exact disjointComplement_inter_eq_zero ((J : Set X))ᵈ ⟨hxJ, hxJd⟩
  -- Since `BSum = J + Jᵈ` as sets, and `BSum` is a band, `BSumᵈᵈ = BSum`.
  have hBSum_dd : (((BSum : Set X))ᵈ)ᵈ = ((BSum : Set X)) :=
    Band.eq_disjointComplement_disjointComplement BSum
  -- `{0}ᵈ = X`.
  have hzero_d : (({0} : Set X))ᵈ = (Set.univ : Set X) := by
    ext x
    refine ⟨fun _ => Set.mem_univ _, fun _ => ?_⟩
    intro a ha
    rw [Set.mem_singleton_iff] at ha
    subst ha
    unfold IsVLDisjoint
    simp
  -- Chain: `BSum = BSumᵈᵈ ⊇ ({0})ᵈ = X` (using `BSumᵈ ⊆ {0}`).
  have hBSum_top : ((BSum : Set X)) = Set.univ := by
    apply Set.Subset.antisymm (Set.subset_univ _)
    rw [← hBSum_dd]
    have : (((BSum : Set X))ᵈ) ⊆ ({0} : Set X) := by
      rw [hBSum]; exact hSumd_zero
    calc (Set.univ : Set X)
        = (({0} : Set X))ᵈ := hzero_d.symm
      _ ⊆ (((BSum : Set X))ᵈ)ᵈ := disjointComplement_anti this
  -- Transfer: `J + Jᵈ = X` as sets.
  have hSum_top : ((OrderIdeal.sum J Jd : OrderIdeal X) : Set X) = Set.univ := by
    rw [← hBSum]; exact hBSum_top
  -- Apply the decomposition characterisation.
  refine (ProjectionBand.projectionBand_iff_add_disjointComplement J).mpr (fun x => ?_)
  have hxmem : x ∈ ((OrderIdeal.sum J Jd : OrderIdeal X) : Set X) := by
    rw [hSum_top]; exact Set.mem_univ _
  obtain ⟨a, ha, b, hb, hab⟩ := Submodule.mem_sup.mp hxmem
  refine ⟨a, b, ha, ?_, hab.symm⟩
  exact (show b ∈ ((J : Set X))ᵈ by rw [← hJd_set]; exact hb)

end BanachLattice
